#!/usr/bin/env bash
# Generated by Quality Playbook v1.5.7 — https://github.com/andrewstellman/quality-playbook
# Author: Andrew Stellman · Date: 2026-06-19 · Project: go-chi/chi v1.5.8
#
# Canonical shell extraction of the method bit-name set FROM reverseMethodMap (tree.go).
# reverseMethodMap is keyed BY the m<NAME> bit (the reverse direction). This is List B'
# for REQ-003: the bits reverseMethodMap claims to reverse. It must equal the methodMap
# bit set (List A) exactly.
#
# Output: one bit identifier per line (e.g. "mGET"), sorted, on stdout.
#
# reverseMethodMap block in tree.go:47-57 — lines of the form:
#     mGET:     http.MethodGet,
set -euo pipefail
TREE="${1:-tree.go}"

awk '
  /var reverseMethodMap = map\[methodTyp\]string\{/ { inblock=1; next }
  inblock && /^\}/ { inblock=0 }
  inblock {
    # line looks like:  mGET:     http.MethodGet,
    # take the token before the colon
    split($0, a, ":")
    bit=a[1]
    gsub(/[ \t,]/, "", bit)
    if (bit ~ /^m[A-Z]+$/) print bit
  }
' "$TREE" | sort -u
