#!/usr/bin/env bash
# Generated by Quality Playbook v1.5.7 — https://github.com/andrewstellman/quality-playbook
# Author: Andrew Stellman · Date: 2026-06-19 · Project: go-chi/chi v1.5.8
#
# Canonical shell extraction of the method bit-name set FROM the mALL aggregate (tree.go).
# mALL is the OR of every method bit. This is List C for REQ-003: the bits the wildcard
# (mALL) registration fans across. It must equal the methodMap bit set exactly — a bit in
# methodMap but missing from mALL is silently dropped from wildcard registration.
#
# Output: one bit identifier per line (e.g. "mGET"), sorted, on stdout.
#
# mALL declaration in tree.go:32-33 (may span multiple lines):
#     var mALL = mCONNECT | mDELETE | mGET | mHEAD |
#         mOPTIONS | mPATCH | mPOST | mPUT | mTRACE
set -euo pipefail
TREE="${1:-tree.go}"

# Grab the mALL declaration (it may span several lines, each continuation line ending
# with `|`). Accumulate every line from `var mALL =` until a line that does NOT end in a
# `|` continuation, then split the accumulated buffer on `|`.
awk '
  /var mALL =/ { inblock=1; buf=""; sub(/^[ \t]*var mALL =/, "") }
  inblock {
    buf = buf " " $0
    # a continuation line ends in `|` (optionally followed by whitespace);
    # the declaration ends on the first line that does NOT.
    if ($0 !~ /\|[ \t]*$/) { print buf; inblock=0 }
  }
' "$TREE" \
  | tr "|" "\n" \
  | tr -d " \t" \
  | grep -E "^m[A-Z]+$" \
  | sort -u
