#!/usr/bin/env bash
# Generated by Quality Playbook v1.5.7 — https://github.com/andrewstellman/quality-playbook
# Author: Andrew Stellman · Date: 2026-06-19 · Project: go-chi/chi v1.5.8
#
# Canonical shell extraction of the method bit-name set FROM methodMap (tree.go).
# This is the authoritative code-side List A for REQ-003 (HTTP-method closed-set
# enumeration). It extracts the `m<NAME>` bit identifier used as the VALUE in each
# methodMap entry — these are the bits that mALL must OR together and that
# reverseMethodMap must reverse.
#
# Output: one bit identifier per line (e.g. "mGET"), sorted, on stdout.
#
# methodMap block in tree.go:35-45 — lines of the form:
#     http.MethodGet:     mGET,
set -euo pipefail
TREE="${1:-tree.go}"

# Isolate the methodMap literal block, then pull the second column (the m<NAME> bit).
awk '
  /var methodMap = map\[string\]methodTyp\{/ { inblock=1; next }
  inblock && /^\}/ { inblock=0 }
  inblock {
    # line looks like:  http.MethodGet:     mGET,
    # take the token after the colon, strip the trailing comma/space
    n=split($0, a, ":")
    if (n>=2) {
      bit=a[2]
      gsub(/[ \t,]/, "", bit)
      if (bit ~ /^m[A-Z]+$/) print bit
    }
  }
' "$TREE" | sort -u
