#!/usr/bin/env python3
# Generated by Quality Playbook v1.5.7 — https://github.com/andrewstellman/quality-playbook
# Author: Andrew Stellman · Date: 2026-06-19 · Project: go-chi/chi v1.5.8
#
# Mechanical verification for REQ-003: the HTTP-method closed set must stay consistent
# across methodMap, reverseMethodMap, and mALL (tree.go:32-57).
#
# v1.3.23 invariant: this orchestrator SUBPROCESSES the ORIGINAL shell extraction pipeline
# (extract_methodmap.sh / extract_reversemap.sh / extract_mall.sh). It does NOT reimplement
# the extraction in Python — it runs the shell scripts, captures their stdout, persists each
# list to a *_cases.txt receipt, and diffs the three lists. Reimplementing the awk/sed/grep
# extraction here is forbidden.
#
# Pass criterion: methodMap bits == reverseMethodMap bits == mALL bits (as sets).
# Any asymmetry is a REQ-003 violation (drift) and exits non-zero.
#
# Usage:  python quality/mechanical/verify.py
# Run from the target repo root (the dir containing tree.go).

import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent          # quality/mechanical
REPO_ROOT = HERE.parent.parent                   # target repo root (contains tree.go)
TREE = REPO_ROOT / "tree.go"

EXTRACTORS = {
    "methodMap": HERE / "extract_methodmap.sh",
    "reverseMethodMap": HERE / "extract_reversemap.sh",
    "mALL": HERE / "extract_mall.sh",
}


def run_extractor(name: str, script: Path) -> list[str]:
    """Subprocess the original shell extractor; persist + return its bit list."""
    proc = subprocess.run(
        ["bash", str(script), str(TREE)],
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        print(f"FAIL: extractor for {name} exited {proc.returncode}")
        print(proc.stderr, file=sys.stderr)
        sys.exit(2)
    bits = [ln.strip() for ln in proc.stdout.splitlines() if ln.strip()]
    receipt = HERE / f"{name}_cases.txt"
    receipt.write_text("\n".join(bits) + ("\n" if bits else ""))
    return bits


def main() -> int:
    if not TREE.exists():
        print(f"FAIL: {TREE} not found — run from the target repo root")
        return 2

    lists = {name: set(run_extractor(name, script)) for name, script in EXTRACTORS.items()}

    print("=== REQ-003 method closed-set mechanical verification ===")
    for name, bits in lists.items():
        print(f"  {name}: {len(bits)} bits -> {sorted(bits)}")

    method_bits = lists["methodMap"]
    reverse_bits = lists["reverseMethodMap"]
    mall_bits = lists["mALL"]

    ok = True

    missing_in_reverse = method_bits - reverse_bits
    extra_in_reverse = reverse_bits - method_bits
    if missing_in_reverse or extra_in_reverse:
        ok = False
        print(f"FAIL: methodMap vs reverseMethodMap drift — "
              f"only-in-methodMap={sorted(missing_in_reverse)} "
              f"only-in-reverseMethodMap={sorted(extra_in_reverse)}")

    missing_in_mall = method_bits - mall_bits
    extra_in_mall = mall_bits - method_bits
    if missing_in_mall or extra_in_mall:
        ok = False
        print(f"FAIL: methodMap vs mALL drift — "
              f"only-in-methodMap={sorted(missing_in_mall)} "
              f"only-in-mALL={sorted(extra_in_mall)}")

    if ok:
        print(f"PASS: all three structures enumerate the identical {len(method_bits)}-method "
              f"closed set; mALL ORs every methodMap bit.")
        return 0
    print("RESULT: REQ-003 enumeration drift detected.")
    return 1


if __name__ == "__main__":
    sys.exit(main())
