#!/usr/bin/env python3
# Generated by Quality Playbook v1.5.8 — https://github.com/andrewstellman/quality-playbook
# Author: Andrew Stellman · Date: 2026-06-19 · Project: linux-virtio
#
# Functional tests for the virtio transport/negotiation layer.
#
# The target is Linux kernel C with NO in-tree userspace test harness (validated
# out-of-tree by kselftests/virtme/KVM, none of which ship in this sparse checkout).
# These functional tests are therefore SOURCE-INSPECTION tests: they read the actual
# driver source files and assert on the presence/absence of specific code patterns
# (case labels, poll loops, return-value propagation). This is deterministic, fast,
# and executable — the appropriate form for a no-harness kernel target (SKILL.md
# File 7: "Projects without test infrastructure ... extract the target function,
# write a self-contained test").
#
# Code-side facts are extracted FROM THE SOURCE, never copied from REQUIREMENTS.md or
# CONTRACTS.md (QUALITY.md coverage-theater rule). The authoritative case list comes
# from quality/mechanical/vring_transport_features_cases.txt, produced by the shell
# extraction in quality/mechanical/verify.py (v1.3.23 invariant).
#
# Run:  python3 -m pytest -xvs quality/test_functional.py
#   or: python3 quality/test_functional.py   (self-contained fallback runner)

import re
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
DRIVERS = REPO / "drivers" / "virtio"
CONFIG_H = REPO / "include" / "uapi" / "linux" / "virtio_config.h"
MECH_CASES = REPO / "quality" / "mechanical" / "vring_transport_features_cases.txt"


# --------------------------------------------------------------------------- #
# Helpers — read source, slice function bodies, never copy from artifacts      #
# --------------------------------------------------------------------------- #

def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="ignore")


def _func_body(source: str, signature_regex: str) -> str:
    """Return the text of a C function body from its signature to the first
    line that is a lone closing brace at column 0. Mirrors the awk
    `/sig/,/^}$/` slice used by quality/mechanical/verify.py."""
    lines = source.splitlines()
    start = None
    for i, line in enumerate(lines):
        if re.search(signature_regex, line):
            start = i
            break
    assert start is not None, f"signature not found: {signature_regex}"
    body = [lines[start]]
    for line in lines[start + 1:]:
        body.append(line)
        if line == "}":
            break
    return "\n".join(body)


def _case_labels(func_body: str) -> set:
    labels = set()
    for line in func_body.splitlines():
        s = line.strip()
        if s.startswith("case ") and s.endswith(":"):
            labels.add(s[len("case "):-1].strip())
    return labels


def _header_transport_bits() -> dict:
    """name -> int value, for #defines with value in [28, 42)."""
    bits = {}
    for line in _read(CONFIG_H).splitlines():
        m = re.match(r"#define\s+(VIRTIO_(?:RING_)?F_[A-Z0-9_]+)\s+(\d+)", line)
        if m:
            name, val = m.group(1), int(m.group(2))
            if 28 <= val < 42:
                bits[name] = val
    return bits


# ============================================================================ #
# GROUP 1 — Spec requirements (one test per testable REQ section)              #
# ============================================================================ #

class TestSpecRequirements:
    """One test per testable requirement from quality/REQUIREMENTS.md."""

    def test_req002_whitelist_clears_unenumerated_via_default(self):
        """[Req: inferred — REQ-002] vring_transport_features clears any
        transport bit not enumerated, via __virtio_clear_bit in default:."""
        body = _func_body(_read(DRIVERS / "virtio_ring.c"),
                          r"void\s+vring_transport_features")
        assert "default:" in body, "whitelist must have a default branch"
        assert "__virtio_clear_bit" in body, \
            "default branch must clear unenumerated bits"

    def test_req002_case_set_is_exactly_the_known_eight(self):
        """[Req: inferred — REQ-002] The closed set is the 8 enumerated bits;
        extracted FROM SOURCE, not from REQUIREMENTS.md."""
        body = _func_body(_read(DRIVERS / "virtio_ring.c"),
                          r"void\s+vring_transport_features")
        labels = _case_labels(body)
        expected = {
            "VIRTIO_RING_F_INDIRECT_DESC", "VIRTIO_RING_F_EVENT_IDX",
            "VIRTIO_F_VERSION_1", "VIRTIO_F_ACCESS_PLATFORM",
            "VIRTIO_F_RING_PACKED", "VIRTIO_F_ORDER_PLATFORM",
            "VIRTIO_F_NOTIFICATION_DATA", "VIRTIO_F_IN_ORDER",
        }
        assert labels == expected, f"case set drifted: {labels ^ expected}"

    def test_req001_core_preserve_loop_readds_transport_bits(self):
        """[Req: inferred — REQ-001] The core re-adds every device-offered
        transport bit before calling per-transport finalize."""
        src = _read(DRIVERS / "virtio.c")
        assert "VIRTIO_TRANSPORT_F_START" in src and "VIRTIO_TRANSPORT_F_END" in src
        assert "__virtio_set_bit" in src, \
            "core must set (preserve) transport bits before finalize"
        assert "finalize_features" in src

    def test_req003_pci_modern_reset_polls_for_status_zero(self):
        """[Req: Tier-4 — REQ-003] PCI-modern vp_reset polls until status==0."""
        body = _func_body(_read(DRIVERS / "virtio_pci_modern.c"),
                          r"\bvp_reset\b")
        assert "while" in body and "get_status" in body, \
            "vp_reset must poll status (the spec §5 reference impl)"

    def test_req004_mmio_interrupt_sets_handled_on_config(self):
        """[Req: inferred — REQ-004] MMIO vm_interrupt returns IRQ_HANDLED on
        config — the conformant reference."""
        body = _func_body(_read(DRIVERS / "virtio_mmio.c"), r"\bvm_interrupt\b")
        assert "IRQ_HANDLED" in body
        assert "INT_CONFIG" in body or "VIRTIO_MMIO_INT_CONFIG" in body

    def test_req006_features_ok_rechecks_for_version_1(self):
        """[Req: Tier-4 — REQ-006] virtio_features_ok sets and re-reads
        FEATURES_OK for modern devices, early-returns for legacy."""
        body = _func_body(_read(DRIVERS / "virtio.c"), r"virtio_features_ok")
        assert "VIRTIO_CONFIG_S_FEATURES_OK" in body
        assert "VIRTIO_F_VERSION_1" in body, \
            "legacy early-return must gate on VERSION_1"

    def test_req008_ring_has_write_barriers(self):
        """[Req: Tier-4 — REQ-008] The ring uses write barriers between
        descriptor writes and index updates."""
        src = _read(DRIVERS / "virtio_ring.c")
        assert "virtio_wmb" in src, "ring must issue write barriers"

    def test_req002_mechanical_receipt_exists_and_lists_eight_cases(self):
        """[Req: inferred — REQ-002 / REQ-016] The mechanical extraction
        receipt exists and is the authoritative code-side list."""
        assert MECH_CASES.is_file(), \
            "quality/mechanical/vring_transport_features_cases.txt must exist"
        receipt_labels = _case_labels(_read(MECH_CASES))
        assert len(receipt_labels) == 8, \
            f"receipt should list 8 case labels, got {len(receipt_labels)}"


# ============================================================================ #
# GROUP 2 — Fitness scenarios (1:1 with QUALITY.md scenarios)                  #
# ============================================================================ #

class TestFitnessScenarios:
    """One test per QUALITY.md fitness-to-purpose scenario, named to match."""

    def test_scenario_1_mmio_finalize_preserves_ring_reset(self):
        """[Req: inferred — QUALITY.md Scenario 1] MMIO vm_finalize_features
        should re-add RING_RESET after vring_transport_features clears it.

        This asserts the DESIRED behavior; it is expected to FAIL on current
        source (the bug), so it is a candidate-bug detector. Marked xfail."""
        body = _func_body(_read(DRIVERS / "virtio_mmio.c"),
                          r"\bvm_finalize_features\b")
        assert "vring_transport_features" in body
        # Desired: a re-add of RING_RESET after the whitelist call.
        post = body.split("vring_transport_features", 1)[1]
        if "VIRTIO_F_RING_RESET" not in post:
            pytest.xfail("BUG candidate: vm_finalize_features does not "
                         "re-preserve RING_RESET (REQ-001)")
        assert "VIRTIO_F_RING_RESET" in post

    def test_scenario_2_notif_config_data_preserved_if_validated(self):
        """[Req: inferred — QUALITY.md Scenario 2] If vp_check_common_size
        validates NOTIF_CONFIG_DATA, vp_transport_features must re-add bit 39."""
        src = _read(DRIVERS / "virtio_pci_modern.c")
        check_body = _func_body(src, r"\bvp_check_common_size\b")
        trans_body = _func_body(src, r"\bvp_transport_features\b")
        if "VIRTIO_F_NOTIF_CONFIG_DATA" in check_body:
            if "VIRTIO_F_NOTIF_CONFIG_DATA" not in trans_body:
                pytest.xfail("BUG candidate: NOTIF_CONFIG_DATA validated by "
                             "vp_check_common_size but never re-added by "
                             "vp_transport_features (REQ-005)")
            assert "VIRTIO_F_NOTIF_CONFIG_DATA" in trans_body

    def test_scenario_3_mmio_reset_waits_for_status_zero(self):
        """[Req: Tier-4 — QUALITY.md Scenario 3] vm_reset must poll status
        until it reads 0 (spec §5)."""
        body = _func_body(_read(DRIVERS / "virtio_mmio.c"), r"\bvm_reset\b")
        has_poll = "while" in body and ("STATUS" in body or "readl" in body)
        if not has_poll:
            pytest.xfail("BUG candidate: vm_reset has no status poll loop "
                         "(REQ-003 / spec §5)")
        assert has_poll

    def test_scenario_4_pci_config_interrupt_returns_handled(self):
        """[Req: inferred — QUALITY.md Scenario 4] vp_interrupt must propagate
        IRQ_HANDLED from the config-change branch."""
        body = _func_body(_read(DRIVERS / "virtio_pci_common.c"),
                          r"\bvp_interrupt\b")
        assert "vp_config_changed" in body
        # Desired: the config branch's IRQ_HANDLED is captured or returned,
        # not discarded as a bare call statement.
        captures = bool(re.search(r"=\s*vp_config_changed", body)) \
            or bool(re.search(r"ret\s*\|?=.*IRQ_HANDLED", body))
        bare_call = bool(re.search(r"^\s*vp_config_changed\s*\(", body, re.M))
        if bare_call and not captures:
            pytest.xfail("BUG candidate: vp_interrupt discards "
                         "vp_config_changed's IRQ_HANDLED return (REQ-004)")
        assert captures

    def test_scenario_5_vdpa_finalize_preserves_ring_reset(self):
        """[Req: inferred — QUALITY.md Scenario 5] vDPA finalize should
        re-preserve RING_RESET before vdpa_set_features."""
        body = _func_body(_read(DRIVERS / "virtio_vdpa.c"),
                          r"virtio_vdpa_finalize_features")
        assert "vring_transport_features" in body
        post = body.split("vring_transport_features", 1)[1]
        if "VIRTIO_F_RING_RESET" not in post:
            pytest.xfail("BUG candidate: virtio_vdpa_finalize_features does "
                         "not re-preserve RING_RESET (REQ-001)")
        assert "VIRTIO_F_RING_RESET" in post

    def test_scenario_6_whitelist_enumeration_matches_known_gap(self):
        """[Req: inferred — QUALITY.md Scenario 6] The diff between header
        transport bits and case labels is exactly the known {37,39,40,41}
        compensation set — a new entry means a bit was added to the header
        without updating the switch."""
        body = _func_body(_read(DRIVERS / "virtio_ring.c"),
                          r"void\s+vring_transport_features")
        labels = _case_labels(body)
        header = _header_transport_bits()
        missing = {v for n, v in header.items() if n not in labels}
        # Bits 28/29 are RING_F_* whose #defines live in another header, but
        # their case labels ARE present, so they never appear as missing.
        assert missing == {37, 39, 40, 41}, \
            f"whitelist gap changed from the known set: {missing}"

    def test_scenario_7_packed_wrap_toggles_counter_and_flags(self):
        """[Req: inferred — QUALITY.md Scenario 7] The packed wrap site mutates
        both the wrap counter and the avail/used flags."""
        src = _read(DRIVERS / "virtio_ring.c")
        assert "avail_wrap_counter" in src
        assert "avail_used_flags" in src

    def test_scenario_8_legacy_reset_divergence_documented(self):
        """[Req: Tier-4 — QUALITY.md Scenario 8] The legacy reset single-read
        divergence is documented as intentional (in REQUIREMENTS.md REQ-003
        cond 4), distinguishing it from the MMIO accidental omission."""
        reqs = _read(REPO / "quality" / "REQUIREMENTS.md")
        assert "PCI-legacy" in reqs and "intentional" in reqs.lower(), \
            "legacy reset exemption must be documented in REQUIREMENTS.md"


# ============================================================================ #
# GROUP 3 — Boundaries and edge cases (defensive patterns)                     #
# ============================================================================ #

class TestBoundariesAndEdgeCases:
    """One test per defensive/boundary pattern from the negotiation surface."""

    def test_legacy_finalize_is_32bit_bounded(self):
        """[Req: inferred — from vp_finalize_features(legacy) BUG_ON guard]
        Legacy finalize guards against >32-bit features (bits 37-41 out of
        range), which is why it is exempt from the compensation requirement."""
        body = _func_body(_read(DRIVERS / "virtio_pci_legacy.c"),
                          r"\bvp_finalize_features\b")
        assert "BUG_ON" in body or "vring_transport_features" in body

    def test_transport_range_boundaries_are_28_and_42(self):
        """[Req: inferred — from VIRTIO_TRANSPORT_F_START/END] The transport
        range boundaries are the values the whitelist loop iterates over."""
        src = _read(CONFIG_H)
        assert re.search(r"#define\s+VIRTIO_TRANSPORT_F_START\s+28", src)
        assert re.search(r"#define\s+VIRTIO_TRANSPORT_F_END\s+42", src)

    def test_features_ok_legacy_returns_before_setting_features_ok(self):
        """[Req: inferred — from virtio_features_ok legacy early-return] The
        legacy branch returns 0 BEFORE FEATURES_OK is set (no acceptance
        confirmation by design)."""
        body = _func_body(_read(DRIVERS / "virtio.c"), r"virtio_features_ok")
        idx_version = body.find("VIRTIO_F_VERSION_1")
        idx_features_ok = body.find("VIRTIO_CONFIG_S_FEATURES_OK")
        assert idx_version != -1 and idx_features_ok != -1
        assert idx_version < idx_features_ok, \
            "VERSION_1 gate must precede the FEATURES_OK set/recheck"

    def test_zero_isr_returns_irq_none(self):
        """[Req: inferred — from vp_interrupt isr==0 guard] A zero ISR returns
        IRQ_NONE (correct spurious-interrupt rejection)."""
        body = _func_body(_read(DRIVERS / "virtio_pci_common.c"),
                          r"\bvp_interrupt\b")
        assert "IRQ_NONE" in body, "vp_interrupt must reject a zero ISR"

    def test_vdpa_reset_delegates_to_backend(self):
        """[Req: inferred — from virtio_vdpa_reset delegation] vDPA reset
        delegates the wait to the backend; guest reinit must not assume sync."""
        body = _func_body(_read(DRIVERS / "virtio_vdpa.c"),
                          r"virtio_vdpa_reset")
        assert "vdpa" in body.lower()

    def test_mmio_finalize_writes_driver_features_register(self):
        """[Req: inferred — from vm_finalize_features register write] MMIO
        finalize writes negotiated features to the DRIVER_FEATURES register —
        the write that publishes whatever survived the whitelist."""
        body = _func_body(_read(DRIVERS / "virtio_mmio.c"),
                          r"\bvm_finalize_features\b")
        assert "DRIVER_FEATURES" in body or "writel" in body

    def test_pci_modern_compensator_readds_three_bits(self):
        """[Req: inferred — from vp_transport_features re-add set] The modern
        compensator re-adds SR_IOV/RING_RESET/ADMIN_VQ — boundary check that it
        covers 37/40/41 (and the bit-39 gap is real)."""
        body = _func_body(_read(DRIVERS / "virtio_pci_modern.c"),
                          r"\bvp_transport_features\b")
        for bit in ("VIRTIO_F_SR_IOV", "VIRTIO_F_RING_RESET", "VIRTIO_F_ADMIN_VQ"):
            assert bit in body, f"compensator should re-add {bit}"


# Self-contained fallback runner (when pytest is unavailable)
if __name__ == "__main__":
    import sys
    try:
        raise SystemExit(pytest.main([__file__, "-v"]))
    except Exception as exc:  # pragma: no cover
        sys.stderr.write(f"pytest unavailable ({exc}); run via "
                         "`python3 -m pytest quality/test_functional.py`\n")
        raise
