#!/usr/bin/env python3
# Generated by Quality Playbook v1.5.8 — https://github.com/andrewstellman/quality-playbook
# Author: Andrew Stellman · Date: 2026-06-19 · Project: linux-virtio
#
# Regression tests for the THREE bugs confirmed in Phase 3 (Code Review).
# Same framework + style as quality/test_functional.py: source-inspection pytest
# tests that read the actual driver source and assert on the presence/absence of
# the exact code pattern each finding cites. This is the appropriate form for a
# no-userspace-harness kernel target (SKILL.md File 7).
#
# Each test asserts the DESIRED CORRECT behavior, so it FAILS (XFAIL strict) on the
# current buggy source and XPASSes — a strict failure that forces removing the guard —
# once the corresponding quality/patches/BUG-NNN-fix.patch is applied.
#
# Tests are NOT marked run=False: they execute, read files, and string-match.
# An inert test is the worst state (v1.3.18 BUG-004 regression).
#
# Run:  python3 -m pytest -xvs quality/test_regression.py

import re
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
DRIVERS = REPO / "drivers" / "virtio"


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="ignore")


def _func_body(source: str, signature_regex: str) -> str:
    """Slice a C function from its signature to the first lone closing brace at
    column 0 (mirrors quality/mechanical/verify.py and test_functional.py)."""
    lines = source.splitlines()
    start = None
    for i, line in enumerate(lines):
        if re.search(signature_regex, line):
            start = i
            break
    assert start is not None, f"signature not found: {signature_regex}"
    body = [lines[start]]
    for line in lines[start + 1:]:
        body.append(line)
        if line == "}":
            break
    return "\n".join(body)


class TestRegressionConfirmedBugs:
    """One strict-xfail regression test per confirmed BUG-NNN."""

    @pytest.mark.xfail(strict=True,
        reason="BUG-001: vp_transport_features never re-adds VIRTIO_F_NOTIF_CONFIG_DATA(39) "
               "though vring_transport_features clears it and vp_check_common_size validates it "
               "— unskip after applying quality/patches/BUG-001-fix.patch")
    def test_bug001_pci_compensator_readds_notif_config_data(self):
        """BUG-001. vring_transport_features clears bit 39 (no case label -> default),
        so the PCI compensator vp_transport_features MUST re-add VIRTIO_F_NOTIF_CONFIG_DATA
        the same way it re-adds SR_IOV / RING_RESET / ADMIN_VQ. It does not."""
        src = _read(DRIVERS / "virtio_pci_modern.c")
        body = _func_body(src, r"static void vp_transport_features\(")
        # Sanity: this is the compensator (it re-adds at least RING_RESET today).
        assert "VIRTIO_F_RING_RESET" in body, "wrong function sliced"
        # Desired correct behavior: bit 39 is re-added here too.
        assert "VIRTIO_F_NOTIF_CONFIG_DATA" in body, (
            "vp_transport_features does not re-add VIRTIO_F_NOTIF_CONFIG_DATA(39); "
            "the bit stays cleared by vring_transport_features even though "
            "vp_check_common_size validates queue_notify_data (BUG-001)")

    @pytest.mark.xfail(strict=True,
        reason="BUG-002: vp_interrupt discards vp_config_changed's IRQ_HANDLED and returns "
               "vp_vring_interrupt (IRQ_NONE for a config-only interrupt) "
               "— unskip after applying quality/patches/BUG-002-fix.patch")
    def test_bug002_vp_interrupt_returns_handled_on_config(self):
        """BUG-002. On a config-change-only interrupt, vp_interrupt must report
        IRQ_HANDLED. Today the vp_config_changed(...) call's return value is discarded
        and the function returns vp_vring_interrupt(...), which is IRQ_NONE when no vq
        is serviced. The fix must capture/OR the config handler's IRQ_HANDLED into the
        returned value (e.g. `ret = vp_config_changed(...)` then `ret |= vp_vring_interrupt(...)`
        or an explicit IRQ_HANDLED merge)."""
        src = _read(DRIVERS / "virtio_pci_common.c")
        body = _func_body(src, r"static irqreturn_t vp_interrupt\(")
        # Sanity: this is the dispatcher that calls vp_config_changed.
        assert "vp_config_changed" in body, "wrong function sliced"
        # Locate the config dispatch and verify its result feeds the return value.
        config_calls = [ln.strip() for ln in body.splitlines()
                        if "vp_config_changed(" in ln]
        assert config_calls, "no vp_config_changed call in vp_interrupt"
        # Desired: the config call's return is assigned/merged, not a bare statement.
        # A bare `vp_config_changed(irq, opaque);` (no '=' or '|=' or 'return') means
        # its IRQ_HANDLED is dropped — the bug.
        merged = any(("=" in ln) or ln.startswith("return ")
                     for ln in config_calls)
        assert merged, (
            "vp_config_changed() result is discarded in vp_interrupt; a config-only "
            "interrupt returns IRQ_NONE via vp_vring_interrupt (BUG-002)")

    @pytest.mark.xfail(strict=True,
        reason="BUG-003: vm_reset writes 0 to STATUS but never polls for a status read of 0 "
               "(spec section 5) — unskip after applying quality/patches/BUG-003-fix.patch")
    def test_bug003_vm_reset_polls_for_status_zero(self):
        """BUG-003. Per virtio spec §5, after writing 0 to device status the driver MUST
        wait for a read of device_status to return 0 (as vp_reset polls with
        `while (vp_modern_get_status(mdev)) msleep(1)`). vm_reset does not poll."""
        src = _read(DRIVERS / "virtio_mmio.c")
        body = _func_body(src, r"static void vm_reset\(")
        assert "VIRTIO_MMIO_STATUS" in body, "wrong function sliced"
        # Desired correct behavior: a read-back poll loop on the status register.
        has_poll = bool(re.search(r"while\s*\(.*readl\(.*VIRTIO_MMIO_STATUS", body)) or (
            "while" in body and "readl" in body and "VIRTIO_MMIO_STATUS" in body)
        assert has_poll, (
            "vm_reset writes 0 to VIRTIO_MMIO_STATUS but has no `while (readl(...STATUS))` "
            "wait-for-zero poll; spec §5 reset contract unmet (BUG-003)")


if __name__ == "__main__":
    import sys
    sys.exit(pytest.main([__file__, "-v"]))
