# Generated by Quality Playbook v1.5.6 — https://github.com/andrewstellman/quality-playbook
# Author: Andrew Stellman · Date: 2026-05-08 · Project: QPB

from __future__ import annotations

import json
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from bin import archive_lib, bootstrap_self_audit_docs as bootstrap_docs
from bin import reference_docs_ingest as rdi
from bin import role_map, run_playbook, run_state_lib


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _raw_role_map_payload() -> dict:
    return {
        "schema_version": role_map.SCHEMA_VERSION,
        "files": [
            {
                "path": "bin/run_playbook.py",
                "role": "code",
                "size_bytes": 100,
                "rationale": "core orchestrator code",
            },
            {
                "path": "quality/EXPLORATION.md",
                "role": "playbook-output",
                "size_bytes": 900,
                "rationale": "historical playbook artifact",
            },
        ],
        "provenance": "git-ls-files",
    }


class RequirementAssertionsMixin:
    def assert_req_001_treats_cite_only_docs_as_docs_backed_input(self) -> None:
        """[Req: inferred — REQ-001] cite-only plaintext docs count as docs-backed input."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp)
            cite = repo / "reference_docs" / "cite"
            cite.mkdir(parents=True)
            (cite / "spec.md").write_text("# Spec\n", encoding="utf-8")
            self.assertEqual(run_playbook._evaluate_documentation_state(repo), "with_docs")
            self.assertTrue(
                run_playbook.docs_present(repo),
                "startup warning paths should recognize cite-only docs as documentation input",
            )

    def assert_req_002_uses_one_recognized_docs_predicate(self) -> None:
        """[Req: inferred — REQ-002] warnings and doc-state evaluation share one predicate."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp)
            refs = repo / "reference_docs"
            refs.mkdir()
            (refs / "README.md").write_text("ignore me\n", encoding="utf-8")
            self.assertEqual(run_playbook._evaluate_documentation_state(repo), "code_only")
            self.assertFalse(
                run_playbook.docs_present(repo),
                "README-only trees should not suppress the code-only warning path",
            )
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp)
            refs = repo / "reference_docs"
            refs.mkdir()
            (refs / "spec.pdf").write_bytes(b"%PDF-1.4\n")
            self.assertEqual(run_playbook._evaluate_documentation_state(repo), "code_only")
            self.assertFalse(
                run_playbook.docs_present(repo),
                "binary-only trees should not count as recognized documentation",
            )

    def assert_req_003_limits_tier4_ingest_to_top_level_plaintext(self) -> None:
        """[Req: inferred — REQ-003] nested non-cite directories stay out of Tier 4 context."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp)
            refs = repo / "reference_docs"
            (refs / "cite").mkdir(parents=True)
            (refs / "top.md").write_text("top\n", encoding="utf-8")
            (refs / "nested" / "archive").mkdir(parents=True)
            (refs / "nested" / "archive" / "notes.md").write_text("nested\n", encoding="utf-8")
            tier4 = rdi.load_tier4_context(repo)
            self.assertEqual(
                tier4,
                [("reference_docs/top.md", "top\n")],
                "only top-level plaintext docs should appear in Tier 4 context",
            )

    def assert_req_004_preserves_citable_vs_context_placement(self) -> None:
        """[Req: inferred — REQ-004] bootstrap mirroring keeps cite/ docs in cite/."""
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            source = root / "docs_gathered"
            dest = root / "reference_docs"
            (source / "cite").mkdir(parents=True)
            (source / "notes.md").write_text("# Notes\n", encoding="utf-8")
            (source / "cite" / "spec.md").write_text("# Spec\n", encoding="utf-8")
            with mock.patch.object(bootstrap_docs, "SOURCE_DIR", source), mock.patch.object(
                bootstrap_docs, "DEST_DIR", dest
            ):
                rc = bootstrap_docs.main()
            self.assertEqual(rc, 0)
            self.assertTrue((dest / "notes.md").is_file())
            self.assertTrue(
                (dest / "cite" / "spec.md").is_file(),
                "bootstrap mirroring must preserve cite/ formal-doc placement",
            )

    def assert_req_005_enforces_the_full_phase1_gate_mechanically(self) -> None:
        """[Req: inferred — REQ-005] Phase 1 mechanical validation is not length-only."""
        with tempfile.TemporaryDirectory() as tmp:
            quality = Path(tmp) / "quality"
            quality.mkdir()
            filler = "\n".join(f"line {i}" for i in range(1, 123))
            _write(
                quality / "EXPLORATION.md",
                "# Exploration Findings\n\n## Open Exploration Findings\n\n" + filler + "\n",
            )
            ok, _reason = run_state_lib.validate_phase_artifacts(quality, 1)
            self.assertFalse(
                ok,
                "a 120+ line exploration file that omits mandatory sections must be rejected",
            )

    def assert_req_006_parses_canonical_titled_bug_headings(self) -> None:
        """[Req: inferred — REQ-006] archive summaries count titled BUG headings."""
        with tempfile.TemporaryDirectory() as tmp:
            run_folder = Path(tmp)
            _write(
                run_folder / "quality" / "BUGS.md",
                "# Bugs\n\n### BUG-001: Cite-only docs trigger false code-only warning\n\n**Severity**: HIGH\n",
            )
            counts = archive_lib._extract_bug_counts(run_folder)
            self.assertEqual(counts["HIGH"], 1)

    def assert_req_007_normalizes_direct_phase1_role_maps(self) -> None:
        """[Req: inferred — REQ-007] raw direct-output role maps normalize into gate shape."""
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "quality" / "exploration_role_map.json"
            _write(path, json.dumps(_raw_role_map_payload(), indent=2) + "\n")
            ok, errs = role_map.normalize_role_map_for_gate(path)
            self.assertTrue(ok, f"normalization failed: {errs}")
            data = role_map.load_role_map(path)
            self.assertIsNotNone(data)
            self.assertEqual(role_map.validate_role_map(data), [])

    def assert_req_008_keeps_playbook_output_out_of_intrinsic_surface_accounting(self) -> None:
        """[Req: inferred — REQ-008] playbook-output contributes only to other_share."""
        breakdown = role_map.compute_breakdown(_raw_role_map_payload()["files"])
        self.assertAlmostEqual(breakdown["percentages"]["code_share"], 0.1, places=6)
        self.assertAlmostEqual(breakdown["percentages"]["other_share"], 0.9, places=6)
        self.assertEqual(breakdown["files_by_role"]["playbook-output"], 1)


class SpecRequirementTests(RequirementAssertionsMixin, unittest.TestCase):
    def test_req_001_treats_cite_only_docs_as_docs_backed_input(self) -> None:
        self.assert_req_001_treats_cite_only_docs_as_docs_backed_input()

    def test_req_002_uses_one_recognized_docs_predicate(self) -> None:
        self.assert_req_002_uses_one_recognized_docs_predicate()

    def test_req_003_limits_tier4_ingest_to_top_level_plaintext(self) -> None:
        self.assert_req_003_limits_tier4_ingest_to_top_level_plaintext()

    def test_req_004_preserves_citable_vs_context_placement(self) -> None:
        self.assert_req_004_preserves_citable_vs_context_placement()

    def test_req_005_enforces_the_full_phase1_gate_mechanically(self) -> None:
        self.assert_req_005_enforces_the_full_phase1_gate_mechanically()

    def test_req_006_parses_canonical_titled_bug_headings(self) -> None:
        self.assert_req_006_parses_canonical_titled_bug_headings()

    def test_req_007_normalizes_direct_phase1_role_maps(self) -> None:
        self.assert_req_007_normalizes_direct_phase1_role_maps()

    def test_req_008_keeps_playbook_output_out_of_intrinsic_surface_accounting(self) -> None:
        self.assert_req_008_keeps_playbook_output_out_of_intrinsic_surface_accounting()


class FitnessScenarioTests(RequirementAssertionsMixin, unittest.TestCase):
    def test_scenario_1_cite_only_installs_are_not_warned_as_code_only(self) -> None:
        self.assert_req_001_treats_cite_only_docs_as_docs_backed_input()

    def test_scenario_2_readme_only_or_binary_only_trees_do_not_count_as_docs(self) -> None:
        self.assert_req_002_uses_one_recognized_docs_predicate()

    def test_scenario_3_nested_archives_do_not_join_tier4_context(self) -> None:
        self.assert_req_003_limits_tier4_ingest_to_top_level_plaintext()

    def test_scenario_4_bootstrap_mirroring_keeps_the_citable_bucket(self) -> None:
        self.assert_req_004_preserves_citable_vs_context_placement()

    def test_scenario_5_shallow_exploration_does_not_unlock_phase2(self) -> None:
        self.assert_req_005_enforces_the_full_phase1_gate_mechanically()

    def test_scenario_6_archive_metrics_preserve_canonical_bug_counts(self) -> None:
        self.assert_req_006_parses_canonical_titled_bug_headings()

    def test_scenario_7_direct_and_runner_role_maps_converge(self) -> None:
        self.assert_req_007_normalizes_direct_phase1_role_maps()

    def test_scenario_8_historical_quality_output_stays_out_of_code_share(self) -> None:
        self.assert_req_008_keeps_playbook_output_out_of_intrinsic_surface_accounting()


class BoundaryAndEdgeCaseTests(unittest.TestCase):
    def test_boundary_1_reference_docs_plaintext_ignores_readme_and_binary_files(self) -> None:
        """[Req: inferred — from _reference_docs_plaintext()] only recognized plaintext files count."""
        with tempfile.TemporaryDirectory() as tmp:
            refs = Path(tmp) / "reference_docs"
            (refs / "cite").mkdir(parents=True)
            (refs / "README.md").write_text("ignored\n", encoding="utf-8")
            (refs / "notes.md").write_text("keep\n", encoding="utf-8")
            (refs / "cite" / "spec.txt").write_text("keep\n", encoding="utf-8")
            (refs / "design.pdf").write_bytes(b"%PDF\n")
            found = [p.relative_to(refs).as_posix() for p in run_playbook._reference_docs_plaintext(refs)]
            self.assertEqual(found, ["cite/spec.txt", "notes.md"])

    def test_boundary_2_tier4_context_is_sorted(self) -> None:
        """[Req: inferred — from load_tier4_context() ordering] Tier 4 ordering is deterministic."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp)
            refs = repo / "reference_docs"
            (refs / "cite").mkdir(parents=True)
            (refs / "b.md").write_text("b\n", encoding="utf-8")
            (refs / "a.md").write_text("a\n", encoding="utf-8")
            tier4 = rdi.load_tier4_context(repo)
            self.assertEqual([path for path, _ in tier4], ["reference_docs/a.md", "reference_docs/b.md"])

    def test_boundary_3_compute_breakdown_treats_playbook_output_as_other_share(self) -> None:
        """[Req: inferred — from compute_breakdown()] playbook-output never inflates code_share."""
        files = [
            {"path": "bin/tool.py", "role": "code", "size_bytes": 5, "rationale": "code"},
            {"path": "quality/BUGS.md", "role": "playbook-output", "size_bytes": 95, "rationale": "history"},
        ]
        breakdown = role_map.compute_breakdown(files)
        self.assertAlmostEqual(breakdown["percentages"]["code_share"], 0.05, places=6)
        self.assertAlmostEqual(breakdown["percentages"]["other_share"], 0.95, places=6)

    def test_boundary_4_normalize_role_map_recomputes_breakdown_and_summary(self) -> None:
        """[Req: inferred — from normalize_role_map_for_gate()] canonical fields derive from files[]."""
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "quality" / "exploration_role_map.json"
            payload = _raw_role_map_payload()
            payload["breakdown"] = {"files_by_role": {}, "size_by_role": {}, "percentages": {"skill_share": 0, "code_share": 0, "tool_share": 0, "other_share": 1}}
            payload["summary"] = {"file_count": 999}
            _write(path, json.dumps(payload, indent=2) + "\n")
            ok, errs = role_map.normalize_role_map_for_gate(path)
            self.assertTrue(ok, errs)
            data = role_map.load_role_map(path)
            self.assertEqual(data["summary"]["file_count"], 2)
            self.assertEqual(data["breakdown"]["files_by_role"]["code"], 1)

    def test_boundary_5_phase2_validator_accepts_the_generated_contract_shape(self) -> None:
        """[Req: inferred — from validate_phase_artifacts(..., 2)] generated Phase 2 artifacts satisfy the fixed-name contract."""
        ok, reason = run_state_lib.validate_phase_artifacts(REPO_ROOT / "quality", 2)
        self.assertTrue(ok, reason)


if __name__ == "__main__":
    unittest.main()
