#!/usr/bin/env python3
# Generated by Quality Playbook v1.5.8 — https://github.com/andrewstellman/quality-playbook
# Author: Andrew Stellman · Date: 2026-06-19 · Project: linux-virtio
#
# Mechanical verification orchestrator for the vring_transport_features() whitelist.
#
# v1.3.23 INVARIANT: this script MUST subprocess.run the ORIGINAL shell extraction
# pipeline. Reimplementing the awk/grep extraction in Python is FORBIDDEN — the whole
# point is that the code-side List A is produced by the same deterministic shell command
# a human reviewer would run, so the artifact cannot drift from the model's prose.
#
# What it does:
#   1. Runs the canonical shell extraction (awk slices the function body,
#      grep pulls the `case` labels) and writes the result to
#      quality/mechanical/vring_transport_features_cases.txt (List A — code side).
#   2. Runs a second shell extraction over include/uapi/linux/virtio_config.h to
#      produce the authoritative transport-bit set (List B — spec side).
#   3. Diffs the two lists and prints which transport bits are DEFINED-but-NOT-A-CASE,
#      i.e. the bits cleared by the `default:` branch unless a transport compensates.
#
# Exit code is always 0 — this is an evidence-producing extractor, not a pass/fail gate.
# The diff it prints is the input to REQ-002's enumeration check; the gate/Phase 3 reads
# the receipts, not this script's return value.

import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent  # quality/mechanical/ -> quality/ -> repo root
RING_C = REPO / "drivers" / "virtio" / "virtio_ring.c"
CONFIG_H = REPO / "include" / "uapi" / "linux" / "virtio_config.h"
CASES_TXT = HERE / "vring_transport_features_cases.txt"
HEADER_TXT = HERE / "virtio_config_transport_bits.txt"


def run_shell(cmd: str) -> str:
    """Run the ORIGINAL shell pipeline (v1.3.23: do not reimplement in Python)."""
    proc = subprocess.run(
        ["bash", "-c", cmd],
        capture_output=True,
        text=True,
        cwd=str(REPO),
    )
    if proc.returncode != 0:
        sys.stderr.write(f"[verify.py] shell command failed: {cmd}\n{proc.stderr}\n")
    return proc.stdout


def main() -> int:
    # --- List A: code-side case labels (the documented PROGRESS.md extraction) ---
    # awk slices from the function signature to the closing brace; grep keeps `case` lines.
    extract_cases = (
        r"""awk '/void vring_transport_features/,/^}$/' """
        + str(RING_C.relative_to(REPO))
        + r""" | grep -E '^[[:space:]]*case[[:space:]]+'"""
    )
    cases_raw = run_shell(extract_cases)
    CASES_TXT.write_text(cases_raw, encoding="utf-8")

    # --- List B: authoritative transport bits from the header [28,42) ---
    # Pull every VIRTIO_F_* / VIRTIO_RING_F_* #define whose value is in the transport
    # range. We extract all relevant #defines with their numeric values via grep+awk,
    # then the diff below filters to [28,42). (Extraction is still pure shell.)
    extract_header = (
        r"""grep -E '#define[[:space:]]+VIRTIO_(RING_)?F_[A-Z0-9_]+[[:space:]]+[0-9]+' """
        + str(CONFIG_H.relative_to(REPO))
        + r""" | awk '{print $2, $3}'"""
    )
    header_raw = run_shell(extract_header)
    HEADER_TXT.write_text(header_raw, encoding="utf-8")

    # --- Diff (string-only; the extraction itself was shell) ---
    # Normalize case labels: strip leading whitespace, trailing colon, the `case ` prefix.
    code_labels = set()
    for line in cases_raw.splitlines():
        s = line.strip()
        if s.startswith("case ") and s.endswith(":"):
            code_labels.add(s[len("case "):-1].strip())

    # Authoritative transport-range names (value in [28,42)). The header lists ring
    # features (28/29) under VIRTIO_RING_F_* and the rest under VIRTIO_F_*.
    transport_defines = {}
    for line in header_raw.splitlines():
        parts = line.split()
        if len(parts) == 2:
            name, val = parts
            try:
                ival = int(val)
            except ValueError:
                continue
            if 28 <= ival < 42:
                transport_defines[name] = ival

    print("=== verify.py: vring_transport_features enumeration receipt ===")
    print(f"List A (code case labels), {len(code_labels)} entries:")
    for c in sorted(code_labels):
        print(f"  case {c}:")
    print(f"\nList B (authoritative transport bits [28,42)), "
          f"{len(transport_defines)} entries:")
    for name, val in sorted(transport_defines.items(), key=lambda kv: kv[1]):
        present = "FOUND as case label" if name in code_labels else "NOT A CASE LABEL (cleared by default:)"
        print(f"  bit {val}: {name} — {present}")

    missing = sorted(
        ((v, n) for n, v in transport_defines.items() if n not in code_labels)
    )
    print("\n=== Diff: transport bits DEFINED but NOT enumerated as a case ===")
    if missing:
        for val, name in missing:
            print(f"  bit {val}: {name} — relies on a transport compensator or is dropped")
    else:
        print("  (none — whitelist enumerates every defined transport bit)")

    print("\nReceipt written to:")
    print(f"  {CASES_TXT.relative_to(REPO)}")
    print(f"  {HEADER_TXT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
