# Generated by Quality Playbook v1.5.7 — https://github.com/andrewstellman/quality-playbook
# Author: Andrew Stellman · Date: 2026-05-30 · Project: quality-playbook
"""Functional tests for the QPB harness run-lifecycle accounting.

Each test maps 1:1 to a requirement in quality/REQUIREMENTS.md and asserts the
SPEC-CORRECT behavior. Tests for requirements the current code satisfies PASS.
Tests for requirements the current code VIOLATES are marked xfail(strict=False)
with the REQ id and a one-line reason — they encode the correct invariant and
flip to XPASS once the defect is fixed (the Phase-3 regression suite carries the
strict-mode proofs). Run from the QPB repo root: `python3 -m pytest quality/test_functional.py -v`.
"""
import ast
import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from bin.harness import plan_runner as PR  # noqa: E402
from bin.harness import inflight_registry as IR  # noqa: E402
from bin.harness import status as ST  # noqa: E402
from bin.harness import runner as RN  # noqa: E402
from bin.harness.schema import TerminalState  # noqa: E402
import bin.archive_lib as AL  # noqa: E402
import bin.run_state_lib as RSL  # noqa: E402
import bin.council_config as CC  # noqa: E402
import bin.qpb_validate as QV  # noqa: E402


def _func_source(path: Path, func_name: str) -> str:
    """Return the source text of a top-level or nested function by name."""
    src = path.read_text(encoding="utf-8")
    tree = ast.parse(src)
    lines = src.splitlines()
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name == func_name:
            return "\n".join(lines[node.lineno - 1 : node.end_lineno])
    raise AssertionError(f"function {func_name} not found in {path}")


# ── Group: Spec requirements (correct-behavior REQs — expected PASS) ──

def test_req006_acquire_run_slot_honors_provider_cap(tmp_path):
    """REQ-006: with a provider cap of 1 and one active entry, a second
    acquire must time out rather than over-admit."""
    reg = tmp_path / "registry.json"
    IR.acquire_run_slot(
        runner="claude", harness_run_dir=tmp_path, run_index=0,
        started_at="2026-05-30T21:00:00Z", max_per_provider={"anthropic": 1},
        registry_path=reg, max_wait_s=0.0,
    )
    IR.update_pid(harness_run_dir=tmp_path, run_index=0, pid=os.getpid(), registry_path=reg)
    with pytest.raises(TimeoutError):
        IR.acquire_run_slot(
            runner="claude", harness_run_dir=tmp_path, run_index=1,
            started_at="2026-05-30T21:00:01Z", max_per_provider={"anthropic": 1},
            registry_path=reg, max_wait_s=0.3, poll_interval_s=0.05,
        )


def test_req008_write_terminal_status_preserves_existing(tmp_path):
    """REQ-008: the collector must not overwrite a status.json that already
    carries a terminal_state (the supervisor's richer write wins)."""
    run_dir = tmp_path / "run-00"
    run_dir.mkdir()
    (run_dir / "status.json").write_text(json.dumps({
        "state": "DONE", "terminal_state": "ABORTED_PHASE",
        "exit_code": 1, "phase_aborted": 2, "terminal_reason": "quota",
    }), encoding="utf-8")
    PR._write_terminal_status(run_dir, pid=123, started_at="x", ended_at="y",
                              terminal=TerminalState.FAILED, terminal_reason="")
    after = json.loads((run_dir / "status.json").read_text(encoding="utf-8"))
    assert after["terminal_state"] == "ABORTED_PHASE"
    assert after["exit_code"] == 1


def test_req009_stale_quality_dir_requires_recent_marker(tmp_path):
    """REQ-009: a populated quality/ with no recent run_start is stale;
    one with a fresh run_start marker is not."""
    q = tmp_path / "quality"
    q.mkdir()
    (q / "BUGS.md").write_text("# bugs\n", encoding="utf-8")
    stale = QV.check_stale_quality_dir(tmp_path)
    assert stale and stale[0]["code"] == "stale_quality_dir"
    # Add a fresh run_start marker → no longer stale.
    from datetime import datetime, timezone
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    (q / "run_state.jsonl").write_text(
        json.dumps({"event": "run_start", "ts": now}) + "\n", encoding="utf-8")
    assert QV.check_stale_quality_dir(tmp_path) == []


def test_req010_council_members_falls_back_on_malformed(monkeypatch):
    """REQ-010: a malformed council_members override falls back to defaults."""
    import bin.qpb_config as QC
    monkeypatch.setattr(QC, "load_config", lambda: {"council_members": []})
    assert CC.council_members() == CC.DEFAULT_COUNCIL_MEMBERS
    monkeypatch.setattr(QC, "load_config", lambda: {"council_members": "not-a-list"})
    assert CC.council_members() == CC.DEFAULT_COUNCIL_MEMBERS


def test_req011_archive_run_refuses_overwrite(tmp_path):
    """REQ-011: archive_run must refuse to overwrite an existing archive."""
    q = tmp_path / "quality"
    q.mkdir()
    (q / "BUGS.md").write_text("# bugs\n", encoding="utf-8")
    ts = "20260530T210000Z"
    AL.archive_run(tmp_path, ts, status="success", target_role_breakdown={})
    with pytest.raises(AL.ArchiveError):
        AL.archive_run(tmp_path, ts, status="success", target_role_breakdown={})


def test_req012_validate_no_source_edits_flags_outside_quality(tmp_path):
    """REQ-012: a dirty file outside quality/ is a violation; one under
    quality/ is clean."""
    subprocess.run(["git", "init", "-q"], cwd=tmp_path, check=True)
    subprocess.run(["git", "config", "user.email", "t@t.t"], cwd=tmp_path, check=True)
    subprocess.run(["git", "config", "user.name", "t"], cwd=tmp_path, check=True)
    (tmp_path / "src.py").write_text("x=1\n", encoding="utf-8")
    subprocess.run(["git", "add", "-A"], cwd=tmp_path, check=True)
    subprocess.run(["git", "commit", "-qm", "init"], cwd=tmp_path, check=True)
    # Dirty a source file outside quality/.
    (tmp_path / "src.py").write_text("x=2\n", encoding="utf-8")
    ok, viol = RSL.validate_no_source_edits(tmp_path)
    assert ok is False and "src.py" in viol
    # Clean it; dirty only under quality/.
    (tmp_path / "src.py").write_text("x=1\n", encoding="utf-8")
    (tmp_path / "quality").mkdir()
    (tmp_path / "quality" / "out.md").write_text("ok\n", encoding="utf-8")
    ok2, viol2 = RSL.validate_no_source_edits(tmp_path)
    assert ok2 is True and viol2 == []


# ── Group: Fitness scenarios (defect REQs — encode spec-correct invariant) ──

@pytest.mark.xfail(strict=False, reason="REQ-001: collector grades PENDING/pid=None as FAILED on first sweep (BUG-001)")
def test_req001_pending_pidless_not_graded_failed(tmp_path):
    """REQ-001: a within-deadline PENDING/pid=None entry must NOT be graded FAILED."""
    hr = tmp_path
    (hr / "run-00").mkdir()
    entry = {
        "index": 0, "description": "d", "repo": "r", "runner": "claude",
        "model": "opus", "channel": "clone", "mode": "A",
        "run_dir": str(hr / "run-00"), "target_dir": str(hr / "run-00" / "target"),
        "pid": None, "state": "PENDING", "started_at": "", "expect": {},
        "max_duration_s": 3600.0, "stream_path": str(hr / "run-00" / "stream.ndjson"),
    }
    outcome = PR._collect_one_run_detached(entry, hr)
    assert outcome.terminal_state != TerminalState.FAILED.value, (
        "a waiting PENDING/pid=None run within its deadline must not be graded FAILED")


@pytest.mark.xfail(strict=False, reason="REQ-002: retry-launch path omits update_pid (BUG-002)")
def test_req002_retry_launch_calls_update_pid():
    """REQ-002: the collector retry-launch path must call update_pid after spawning."""
    body = _func_source(REPO / "bin" / "harness" / "plan_runner.py", "_retry_pending_runs_once")
    assert "update_pid" in body, (
        "_retry_pending_runs_once must call inflight_registry.update_pid after relaunch")


@pytest.mark.xfail(strict=False, reason="REQ-003: relaunched entry keeps state=PENDING (BUG-003)")
def test_req003_launch_entry_sets_running_state():
    """REQ-003: a relaunched manifest entry must carry a RUNNING state, not stay PENDING."""
    body = _func_source(REPO / "bin" / "harness" / "plan_runner.py", "_launch_one_run_detached")
    # The returned manifest-entry dict must set a state key (so a relaunch flips PENDING→RUNNING).
    assert '"state"' in body, (
        "_launch_one_run_detached's returned entry must include a state key (RUNNING)")


@pytest.mark.xfail(strict=False, reason="REQ-004: _PHASE_ARTIFACTS maps Phase-2 outputs to P4/P5 (BUG-004)")
def test_req004_phase2_artifacts_not_reported_as_phase5(tmp_path):
    """REQ-004: a quality/ holding only Phase-2 Generate outputs resolves to phase 2."""
    q = tmp_path / "quality"
    q.mkdir()
    for name in ("EXPLORATION.md", "REQUIREMENTS.md", "CONTRACTS.md",
                 "COVERAGE_MATRIX.md", "COMPLETENESS_REPORT.md", "QUALITY.md",
                 "RUN_CODE_REVIEW.md"):
        (q / name).write_text("x\n", encoding="utf-8")
    inferred = ST._infer_phase_from_artifacts(tmp_path)
    assert inferred is not None and inferred["phase"] == 2, (
        f"a Phase-2-only quality/ must resolve to phase 2, got {inferred}")


@pytest.mark.xfail(strict=False, reason="REQ-005: pid=0 + malformed started_at is active forever (BUG-005)")
def test_req005_pid0_malformed_started_at_not_active_forever():
    """REQ-005: a pid=0 reservation with an unparseable started_at must not be active forever."""
    entry = {"pid": 0, "started_at": "not-a-real-timestamp", "provider": "anthropic"}
    assert IR._entry_is_active(entry) is False, (
        "a pid=0 entry with a malformed started_at must age out, not stay active forever")


# ── Group: Boundaries / edge cases (true invariants — expected PASS) ──

def test_req001_classify_stream_terminal_missing_file_returns_none(tmp_path):
    """REQ-001 boundary: _classify_stream_terminal returns (None, '') for a missing
    stream — the true fact that lets a pid=None entry fall through to FAILED."""
    state, reason = RN._classify_stream_terminal(tmp_path / "nope.ndjson")
    assert state is None and reason == ""


def test_req007_idempotency_short_circuits_on_grading_json(tmp_path):
    """REQ-007 boundary: with a valid grading.json present, _collect_one_run_detached
    returns the cached verdict without re-polling (idempotency contract C-02)."""
    hr = tmp_path
    rd = hr / "run-00"
    rd.mkdir()
    (rd / "grading.json").write_text(json.dumps({"verdict": "PASS"}), encoding="utf-8")
    entry = {
        "index": 0, "description": "d", "repo": "r", "runner": "claude",
        "model": "opus", "channel": "clone", "mode": "A",
        "run_dir": str(rd), "target_dir": str(rd / "target"),
        "pid": None, "terminal_state": "COMPLETED", "expect": {},
    }
    outcome = PR._collect_one_run_detached(entry, hr)
    assert outcome.result == "PASS"
