# Generated by Quality Playbook v1.5.7 — https://github.com/andrewstellman/quality-playbook
# Author: Andrew Stellman · Date: 2026-05-30 · Project: quality-playbook
"""Regression tests for confirmed harness run-lifecycle bugs (BUG-001..005).

Each test is marked @pytest.mark.xfail(strict=True): with the bug present it
fails → XFAIL (expected); once the corresponding quality/patches/BUG-NNN-fix.patch
is applied it passes → XPASS → strict mode flips that to a failure, signaling the
guard should be removed. Run with --runxfail to see the real RED/GREEN result
during the TDD cycle. Must run under REAL pytest (the repo's local pytest/ shim
has no pytest.mark): `(cd /tmp && python3 -m pytest <repo>/quality/test_regression.py -rA)`.
"""
import ast
import json
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from bin.harness import plan_runner as PR  # noqa: E402
# v1.5.7 174 Phase 6: inflight_registry deleted; this import
# was used by test_bug_005 which is also deleted.
from bin.harness import status as ST  # noqa: E402
from bin.harness.schema import TerminalState  # noqa: E402
import bin.council_semantic_check as CS  # noqa: E402


def _func_source(path: Path, func_name: str) -> str:
    src = path.read_text(encoding="utf-8")
    tree = ast.parse(src)
    lines = src.splitlines()
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name == func_name:
            return "\n".join(lines[node.lineno - 1 : node.end_lineno])
    raise AssertionError(f"function {func_name} not found in {path}")


def test_bug_001_pending_pidless_not_graded_failed(tmp_path):
    (tmp_path / "run-00").mkdir()
    entry = {
        "index": 0, "description": "d", "repo": "r", "runner": "claude",
        "model": "opus", "channel": "clone", "mode": "A",
        "run_dir": str(tmp_path / "run-00"), "target_dir": str(tmp_path / "run-00" / "target"),
        "pid": None, "state": "PENDING", "started_at": "", "expect": {},
        "max_duration_s": 3600.0, "stream_path": str(tmp_path / "run-00" / "stream.ndjson"),
    }
    outcome = PR._collect_one_run_detached(entry, tmp_path)
    assert outcome.terminal_state != TerminalState.FAILED.value


# v1.5.7 174 Phase 6: test_bug_002_retry_launch_calls_update_pid
# DELETED. The `update_pid` mechanism it asserted is gone — the
# 174 pool-only model uses manifest-state transitions instead of
# inflight_registry pid=0 reservations + update_pid. The
# underlying contract (retry path records the spawned pid) is
# now preserved by `_finalize_pool_slot_running` which writes
# state=RUNNING + pid under .manifest.lock; that's covered by
# the broader integration tests in test_collector_retry_165.py.


def test_bug_003_launch_entry_sets_running_state():
    body = _func_source(REPO / "bin" / "harness" / "plan_runner.py", "_launch_one_run_detached")
    assert '"state"' in body


def test_bug_004_phase2_artifacts_resolve_to_phase2(tmp_path):
    q = tmp_path / "quality"
    q.mkdir()
    for name in ("EXPLORATION.md", "REQUIREMENTS.md", "CONTRACTS.md",
                 "COVERAGE_MATRIX.md", "COMPLETENESS_REPORT.md", "QUALITY.md",
                 "RUN_CODE_REVIEW.md"):
        (q / name).write_text("x\n", encoding="utf-8")
    inferred = ST._infer_phase_from_artifacts(tmp_path)
    assert inferred is not None and inferred["phase"] == 2


# v1.5.7 174 Phase 6: test_bug_005_pid0_reservation_write_rejects_unparseable_started_at
# DELETED. The invariant it tested (pid=0 reservations carry
# parseable started_at) lived in inflight_registry which is
# now deleted. The pool-only model has no pid=0 reservations
# — entries transition PENDING → ACQUIRING → RUNNING with pid
# set in one shot on spawn. The 170 methodology (no silent
# defaults) lives on in 177's _entry_to_plan_run hardening
# (test_bug_010_entry_to_plan_run_requires_ref).


def test_bug_006_council_response_trailing_bracket_parses():
    resp = (
        "Here is my review:\n"
        '[{"req_id": "REQ-001", "verdict": "supports", "reasoning": "ok"}]\n'
        "Note: REQ-001 relates to item [2] in the spec."
    )
    entries = CS.parse_member_response("claude-opus-4.7", resp, ["REQ-001"])
    assert [(e.req_id, e.verdict) for e in entries] == [("REQ-001", "supports")]


def test_bug_007_capture_phase_yn_no_false_completion(tmp_path):
    q = tmp_path / "quality"
    q.mkdir()
    for name in ("EXPLORATION.md", "REQUIREMENTS.md", "RUN_CODE_REVIEW.md",
                 "RUN_SPEC_AUDIT.md", "RUN_TDD_TESTS.md", "COMPLETENESS_REPORT.md"):
        (q / name).write_text("x\n", encoding="utf-8")
    yn = PR.capture_phase_yn("", q)
    assert [p for p in ("P3", "P4", "P5", "P6") if yn.get(p) == "Y"] == [], (
        "Phase-2-only tree must not mark P3-P6 complete")


def test_bug_008_collector_retries_pending_on_each_running_terminate(tmp_path, monkeypatch):
    """v1.5.7 171: when a collector is reaping multiple RUNNING
    entries and one of them terminates, _retry_pending_runs_once
    must fire again so a starved PENDING entry can be picked up
    while OTHER RUNNING entries are still being awaited. The 165
    design ran the retry exactly ONCE at collect_harness_run entry;
    this fix ensures the retry fires on every RUNNING termination,
    so a slot freed mid-collection actually unsticks a starved
    PENDING entry. Pre-171 reproduction: harness_runs/20260531T014027Z
    — run-01 (claude/sonnet/express) sat PENDING for 35+ minutes
    after haiku freed its anthropic slot at 01:47:08Z because the
    collector had already done its one retry at 01:45:31Z (before
    haiku exited)."""
    manifest = {
        "plan": {"pools": {"claude": 3},
                 "max_per_provider": {"anthropic": 2}},
        "runs": [
            {
                "index": i, "description": f"d{i}", "repo": "r",
                "runner": "claude", "model": "opus", "channel": "clone",
                "mode": "A", "state": "RUNNING", "pid": 100 + i,
                "run_dir": str(tmp_path / f"run-{i:02d}"),
                "target_dir": str(tmp_path / f"run-{i:02d}" / "target"),
                "started_at": "2026-05-31T00:00:00Z", "expect": {},
                "max_duration_s": 3600.0,
                "stream_path": str(tmp_path / f"run-{i:02d}" / "stream.ndjson"),
            }
            for i in range(3)
        ],
    }
    (tmp_path / "manifest.json").write_text(json.dumps(manifest))
    for i in range(3):
        (tmp_path / f"run-{i:02d}").mkdir()

    retry_calls = []
    def spy_retry(hrd, log=None):
        retry_calls.append(1)
        return 0
    monkeypatch.setattr(PR, "_retry_pending_runs_once", spy_retry)

    def stub_collect(entry, hrd, log=None):
        return PR.RunOutcome(
            index=entry["index"],
            description=entry.get("description", ""),
            repo=entry.get("repo", ""),
            runner=entry.get("runner", ""),
            model=entry.get("model", ""),
            phase_yn={}, gate_verdict="N/A", result="N/A",
            terminal_state="COMPLETED",
        )
    monkeypatch.setattr(PR, "_collect_one_run_detached", stub_collect)

    PR.collect_harness_run(tmp_path)

    assert len(retry_calls) >= 2, (
        f"_retry_pending_runs_once was called {len(retry_calls)} "
        f"times; expected >= 2 (once at entry + once after each "
        f"RUNNING terminate)"
    )


def test_bug_010_entry_to_plan_run_requires_ref():
    """v1.5.7 177 BUG-010: _entry_to_plan_run must raise on a
    manifest entry that omits the `ref` field. Pre-177 it
    silently defaulted to ref='main', masking the 161-A
    writer's omission. Live reproduction on
    harness_runs/20260531T194216Z run-02 (express/master):
    PENDING entry was written without ref → retry path read
    ref='main' silently → prepare's `git switch main` failed
    against express's `master` default branch → ABORTED_PREP
    with terminal_reason "switch 'main' failed: fatal:
    invalid reference: main"."""
    entry = {
        "index": 0, "description": "d", "repo": "r",
        "runner": "claude", "model": "haiku",
        "channel": "clone", "mode": "A",
        # intentionally no "ref" key — mimics the pre-177
        # 161-A writer output that masked the bug.
    }
    with pytest.raises(ValueError, match=r"ref"):
        PR._entry_to_plan_run(entry)


def test_bug_010_pending_manifest_writer_preserves_ref():
    """v1.5.7 177 BUG-010: the 161-A PENDING manifest writer at
    plan_runner.py:3207-3225 must include `ref` so the retry
    path can spawn the run against the original branch. Pre-177
    the writer omitted ref; _entry_to_plan_run silently
    defaulted to 'main'; non-main-branch repos (express/master,
    chi/master) ABORTED_PREP at clone time. Source-inspection
    check: ref must appear in the entry-dict literal."""
    # v1.5.7 174: PENDING-entry writer was extracted to a helper.
    body = _func_source(REPO / "bin" / "harness" / "plan_runner.py", "_make_pending_manifest_entry")
    # The PENDING entry-dict literal must include "ref" with
    # the PlanRun's ref attribute (v1.5.7 174 renamed pr → plan_run
    # in _make_pending_manifest_entry).
    assert '"ref"' in body and (
        "pr.ref" in body or "plan_run.ref" in body), (
        "_make_pending_manifest_entry must include "
        "`\"ref\": plan_run.ref` so retry-spawn has the "
        "original branch. Pre-177 the writer omitted ref."
    )


def test_178_skill_md_mandates_qpb_phase_first_call():
    """v1.5.7 178 Fix A: SKILL.md's qpb_phase emission must be a
    hard MUST, not a soft instruction. Pre-178 the wording said
    'at phase entry' which agents interpreted as 'when I've done
    something meaningful,' leading to 5-10 min of phase=— in
    Mode A status output. Surfaced on
    harness_runs/20260531T234613Z."""
    skill = (REPO / "SKILL.md").read_text(encoding="utf-8")
    assert "qpb_phase" in skill, "SKILL.md missing qpb_phase reference"
    # Locate the canonical instruction section; check for any
    # mandate-strength phrasing within a 1500-char window.
    qpb_section_start = skill.find("qpb_phase")
    qpb_section = skill[qpb_section_start:qpb_section_start + 1500]
    mandate_phrases = [
        "MUST be the first tool call",
        "before any other tool call",
        "first action after the skill is invoked",
        "first invocation after skill load",
    ]
    assert any(p in qpb_section for p in mandate_phrases), (
        f"SKILL.md qpb_phase instruction lacks mandate phrasing. "
        f"Expected one of {mandate_phrases!r} in the section."
    )


def test_bug_009_pending_shortcircuit_does_not_prevent_retry_collect(tmp_path, monkeypatch):
    """v1.5.7 172: when collect_harness_run's parallel-collect loop
    encounters a PENDING+pid=None entry, BUG-001's shortcircuit
    returns RunOutcome(terminal_state='PENDING') — but the run is
    NOT actually done; it's expected to transition to RUNNING via
    the 171 retry path. Pre-172, 171's collected_indices set was
    mutated unconditionally on future return, so the formerly-
    PENDING index was wrongly flagged as 'done.' When 171's retry
    transitioned the entry to RUNNING and looked to submit a new
    collect future for it, the `if idx in collected_indices:
    continue` guard skipped it. The retry-spawned run completed
    silently without grading; manifest stayed at state=RUNNING
    forever. Reproduced on harness_runs/20260531T065821Z — run-00
    (claude/haiku/gson) spawned at 07:41:15Z via retry, ran cleanly
    for 5m02s with result.subtype=success, and was never collected
    because 171's collected_indices set held idx=0 from the
    BUG-001 PENDING shortcircuit at collector start."""
    manifest_path = tmp_path / "manifest.json"
    manifest = {
        "plan": {"pools": {"claude": 3},
                 "max_per_provider": {"anthropic": 2}},
        "runs": [
            {
                "index": 0, "description": "d0", "repo": "r",
                "runner": "claude", "model": "haiku", "channel": "clone",
                "mode": "A", "state": "PENDING", "pid": None,
                "run_dir": str(tmp_path / "run-00"),
                "target_dir": str(tmp_path / "run-00" / "target"),
                "started_at": "2026-05-31T00:00:00Z", "expect": {},
                "max_duration_s": 3600.0,
                "stream_path": str(tmp_path / "run-00" / "stream.ndjson"),
            },
            {
                "index": 1, "description": "d1", "repo": "r",
                "runner": "claude", "model": "opus", "channel": "clone",
                "mode": "A", "state": "RUNNING", "pid": 12345,
                "run_dir": str(tmp_path / "run-01"),
                "target_dir": str(tmp_path / "run-01" / "target"),
                "started_at": "2026-05-31T00:00:00Z", "expect": {},
                "max_duration_s": 3600.0,
                "stream_path": str(tmp_path / "run-01" / "stream.ndjson"),
            },
        ],
    }
    manifest_path.write_text(json.dumps(manifest))
    for i in range(2):
        (tmp_path / f"run-{i:02d}").mkdir()

    # Stub _collect_one_run_detached: track per-index call counts +
    # mimic BUG-001 PENDING shortcircuit for PENDING+pid=None.
    call_log = []
    def stub_collect(entry, hrd, log=None):
        call_log.append((entry["index"], entry.get("state"),
                         entry.get("pid")))
        if (entry.get("state") == "PENDING"
                and entry.get("pid") is None):
            return PR.RunOutcome(
                index=entry["index"],
                description=entry.get("description", ""),
                repo=entry.get("repo", ""),
                runner=entry.get("runner", ""),
                model=entry.get("model", ""),
                phase_yn={f"P{i}": "-" for i in range(7)},
                gate_verdict="N/A", result="PENDING",
                terminal_state="PENDING",
            )
        return PR.RunOutcome(
            index=entry["index"],
            description=entry.get("description", ""),
            repo=entry.get("repo", ""),
            runner=entry.get("runner", ""),
            model=entry.get("model", ""),
            phase_yn={}, gate_verdict="N/A", result="N/A",
            terminal_state="COMPLETED",
        )
    monkeypatch.setattr(PR, "_collect_one_run_detached", stub_collect)

    # Stub _retry_pending_runs_once: first call (entry) no-op; any
    # subsequent call transitions run-00 from PENDING to RUNNING in
    # the manifest. Simulates the orchestrator-side slot free.
    retry_calls = [0]
    def stub_retry(hrd, log=None):
        retry_calls[0] += 1
        if retry_calls[0] >= 2:
            m = json.loads(manifest_path.read_text())
            if m["runs"][0]["state"] == "PENDING":
                m["runs"][0]["state"] = "RUNNING"
                m["runs"][0]["pid"] = 999
                manifest_path.write_text(json.dumps(m))
                return 1
        return 0
    monkeypatch.setattr(PR, "_retry_pending_runs_once", stub_retry)

    PR.collect_harness_run(tmp_path)

    # Count how many times index 0 was sent through the collector.
    # Pre-172: 1 call (PENDING shortcircuit only; retry transition
    # skipped because idx 0 in collected_indices).
    # Post-172: 2 calls (PENDING shortcircuit + re-submitted after
    # retry transitions to RUNNING).
    idx0_calls = [c for c in call_log if c[0] == 0]
    assert len(idx0_calls) >= 2, (
        f"_collect_one_run_detached was called {len(idx0_calls)} "
        f"times for index 0; expected >= 2 (PENDING shortcircuit + "
        f"retry-spawned RUNNING resubmit). Call log: {call_log!r}"
    )
