# Generated by Quality Playbook v1.5.7 — https://github.com/andrewstellman/quality-playbook
# Author: Andrew Stellman · Date: 2026-05-30 · Project: quality-playbook
"""Regression tests for confirmed harness run-lifecycle bugs (BUG-001..005).

Each test is marked @pytest.mark.xfail(strict=True): with the bug present it
fails → XFAIL (expected); once the corresponding quality/patches/BUG-NNN-fix.patch
is applied it passes → XPASS → strict mode flips that to a failure, signaling the
guard should be removed. Run with --runxfail to see the real RED/GREEN result
during the TDD cycle. Must run under REAL pytest (the repo's local pytest/ shim
has no pytest.mark): `(cd /tmp && python3 -m pytest <repo>/quality/test_regression.py -rA)`.
"""
import ast
import json
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from bin.harness import plan_runner as PR  # noqa: E402
from bin.harness import inflight_registry as IR  # noqa: E402
from bin.harness import status as ST  # noqa: E402
from bin.harness.schema import TerminalState  # noqa: E402
import bin.council_semantic_check as CS  # noqa: E402


def _func_source(path: Path, func_name: str) -> str:
    src = path.read_text(encoding="utf-8")
    tree = ast.parse(src)
    lines = src.splitlines()
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name == func_name:
            return "\n".join(lines[node.lineno - 1 : node.end_lineno])
    raise AssertionError(f"function {func_name} not found in {path}")


def test_bug_001_pending_pidless_not_graded_failed(tmp_path):
    (tmp_path / "run-00").mkdir()
    entry = {
        "index": 0, "description": "d", "repo": "r", "runner": "claude",
        "model": "opus", "channel": "clone", "mode": "A",
        "run_dir": str(tmp_path / "run-00"), "target_dir": str(tmp_path / "run-00" / "target"),
        "pid": None, "state": "PENDING", "started_at": "", "expect": {},
        "max_duration_s": 3600.0, "stream_path": str(tmp_path / "run-00" / "stream.ndjson"),
    }
    outcome = PR._collect_one_run_detached(entry, tmp_path)
    assert outcome.terminal_state != TerminalState.FAILED.value


def test_bug_002_retry_launch_calls_update_pid():
    body = _func_source(REPO / "bin" / "harness" / "plan_runner.py", "_retry_pending_runs_once")
    assert "update_pid" in body


def test_bug_003_launch_entry_sets_running_state():
    body = _func_source(REPO / "bin" / "harness" / "plan_runner.py", "_launch_one_run_detached")
    assert '"state"' in body


def test_bug_004_phase2_artifacts_resolve_to_phase2(tmp_path):
    q = tmp_path / "quality"
    q.mkdir()
    for name in ("EXPLORATION.md", "REQUIREMENTS.md", "CONTRACTS.md",
                 "COVERAGE_MATRIX.md", "COMPLETENESS_REPORT.md", "QUALITY.md",
                 "RUN_CODE_REVIEW.md"):
        (q / name).write_text("x\n", encoding="utf-8")
    inferred = ST._infer_phase_from_artifacts(tmp_path)
    assert inferred is not None and inferred["phase"] == 2


@pytest.mark.xfail(strict=True, reason="BUG-005: pid=0 + malformed started_at active forever — confirmed open (no fix patch)")
def test_bug_005_pid0_malformed_started_at_not_active_forever():
    entry = {"pid": 0, "started_at": "not-a-real-timestamp", "provider": "anthropic"}
    assert IR._entry_is_active(entry) is False


def test_bug_006_council_response_trailing_bracket_parses():
    resp = (
        "Here is my review:\n"
        '[{"req_id": "REQ-001", "verdict": "supports", "reasoning": "ok"}]\n'
        "Note: REQ-001 relates to item [2] in the spec."
    )
    entries = CS.parse_member_response("claude-opus-4.7", resp, ["REQ-001"])
    assert [(e.req_id, e.verdict) for e in entries] == [("REQ-001", "supports")]


def test_bug_007_capture_phase_yn_no_false_completion(tmp_path):
    q = tmp_path / "quality"
    q.mkdir()
    for name in ("EXPLORATION.md", "REQUIREMENTS.md", "RUN_CODE_REVIEW.md",
                 "RUN_SPEC_AUDIT.md", "RUN_TDD_TESTS.md", "COMPLETENESS_REPORT.md"):
        (q / name).write_text("x\n", encoding="utf-8")
    yn = PR.capture_phase_yn("", q)
    assert [p for p in ("P3", "P4", "P5", "P6") if yn.get(p) == "Y"] == [], (
        "Phase-2-only tree must not mark P3-P6 complete")
