# Generated by Quality Playbook v1.5.6 — https://github.com/andrewstellman/quality-playbook
# Author: Andrew Stellman · Date: 2026-05-08 · Project: QPB

from __future__ import annotations

import sys
from pathlib import Path
from tempfile import TemporaryDirectory
import unittest
from unittest import mock

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from bin import archive_lib, bootstrap_self_audit_docs as bootstrap_docs
from bin import reference_docs_ingest as rdi
from bin import run_playbook, run_state_lib

try:
    import pytest  # type: ignore
except Exception:  # pragma: no cover - local fallback when only the unittest shim is available
    pytest = None


def xfail(*, reason: str) -> object:
    if pytest is not None and hasattr(pytest, "mark") and hasattr(pytest.mark, "xfail"):
        return pytest.mark.xfail(strict=True, reason=reason)
    return unittest.expectedFailure


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


class CodeReviewRegressionTests(unittest.TestCase):
    @xfail(
        reason=(
            "BUG-001: docs_present() ignores cite-only docs-backed trees; "
            "remove after applying quality/patches/BUG-001-fix.patch"
        )
    )
    def test_bug_001_docs_present_recognizes_cite_only_docs(self) -> None:
        with TemporaryDirectory() as tmp:
            repo = Path(tmp)
            cite = repo / "reference_docs" / "cite"
            cite.mkdir(parents=True)
            (cite / "spec.md").write_text("# Spec\n", encoding="utf-8")
            self.assertTrue(run_playbook.docs_present(repo))

    @xfail(
        reason=(
            "BUG-002: docs_present() counts README-only and binary-only trees as docs; "
            "remove after applying quality/patches/BUG-002-fix.patch"
        )
    )
    def test_bug_002_docs_present_uses_the_recognized_plaintext_predicate(self) -> None:
        with TemporaryDirectory() as tmp:
            repo = Path(tmp)
            refs = repo / "reference_docs"
            refs.mkdir()
            (refs / "README.md").write_text("ignored\n", encoding="utf-8")
            self.assertFalse(run_playbook.docs_present(repo))

        with TemporaryDirectory() as tmp:
            repo = Path(tmp)
            refs = repo / "reference_docs"
            refs.mkdir()
            (refs / "spec.pdf").write_bytes(b"%PDF-1.4\n")
            self.assertFalse(run_playbook.docs_present(repo))

    @xfail(
        reason=(
            "BUG-003: load_tier4_context() ingests nested non-cite archives; "
            "remove after applying quality/patches/BUG-003-fix.patch"
        )
    )
    def test_bug_003_tier4_context_excludes_nested_non_cite_archives(self) -> None:
        with TemporaryDirectory() as tmp:
            repo = Path(tmp)
            refs = repo / "reference_docs"
            (refs / "cite").mkdir(parents=True)
            (refs / "top.md").write_text("top\n", encoding="utf-8")
            (refs / "nested" / "archive").mkdir(parents=True)
            (refs / "nested" / "archive" / "notes.md").write_text("nested\n", encoding="utf-8")
            self.assertEqual(rdi.load_tier4_context(repo), [("reference_docs/top.md", "top\n")])

    @xfail(
        reason=(
            "BUG-004: bootstrap mirror drops cite/ formal docs; "
            "remove after applying quality/patches/BUG-004-fix.patch"
        )
    )
    def test_bug_004_bootstrap_mirror_preserves_cite_subtree(self) -> None:
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            source = root / "docs_gathered"
            dest = root / "reference_docs"
            (source / "cite").mkdir(parents=True)
            (source / "notes.md").write_text("# Notes\n", encoding="utf-8")
            (source / "cite" / "spec.md").write_text("# Spec\n", encoding="utf-8")
            with mock.patch.object(bootstrap_docs, "SOURCE_DIR", source), mock.patch.object(
                bootstrap_docs, "DEST_DIR", dest
            ):
                self.assertEqual(bootstrap_docs.main(), 0)
            self.assertTrue((dest / "notes.md").is_file())
            self.assertTrue((dest / "cite" / "spec.md").is_file())

    @xfail(
        reason=(
            "BUG-005: validate_phase_artifacts(..., 1) accepts structurally shallow exploration files; "
            "remove after applying quality/patches/BUG-005-fix.patch"
        )
    )
    def test_bug_005_phase1_validator_enforces_the_written_gate(self) -> None:
        with TemporaryDirectory() as tmp:
            quality = Path(tmp) / "quality"
            quality.mkdir()
            filler = "\n".join(f"line {i}" for i in range(1, 123))
            _write(
                quality / "EXPLORATION.md",
                "# Exploration Findings\n\n## Open Exploration Findings\n\n" + filler + "\n",
            )
            ok, _reason = run_state_lib.validate_phase_artifacts(quality, 1)
            self.assertFalse(ok)

    @xfail(
        reason=(
            "BUG-006: archive bug counting ignores canonical titled headings; "
            "remove after applying quality/patches/BUG-006-fix.patch"
        )
    )
    def test_bug_006_archive_bug_count_accepts_titled_bug_headings(self) -> None:
        with TemporaryDirectory() as tmp:
            run_folder = Path(tmp)
            _write(
                run_folder / "quality" / "BUGS.md",
                "# Bugs\n\n### BUG-001: Cite-only docs trigger false code-only warning\n\n**Severity**: HIGH\n",
            )
            counts = archive_lib._extract_bug_counts(run_folder)
            self.assertEqual(counts["HIGH"], 1)
