#!/usr/bin/env bash
# Generated by Quality Playbook v1.5.7 — https://github.com/andrewstellman/quality-playbook
# Triage verification probes — executable evidence for each confirmed bug.
# Each probe extracts from SOURCE (not from a saved artifact) and asserts the
# exact divergence, citing line contents. Run from the QPB repo root.
set -u
PR=bin/harness/plan_runner.py
ST=bin/harness/status.py
IR=bin/harness/inflight_registry.py
fail=0
say() { printf '%s\n' "$*"; }

# BUG-001 — _collect_one_run_detached has no PENDING/pid=None guard before the
# pid-is-None→FAILED orphan-poll branch. CONFIRM: the FAILED assignment exists
# and no 'state" == "PENDING"' early-return precedes the orphan loop.
body=$(awk '/^def _collect_one_run_detached/,/^def _write_terminal_status/' "$PR")
if printf '%s' "$body" | grep -q 'terminal = TerminalState.FAILED' \
   && ! printf '%s' "$body" | grep -q 'state.*==.*"PENDING".*pid'; then
  say "CONFIRMED BUG-001: _collect_one_run_detached grades pid=None entries via the FAILED branch with no PENDING guard"
else fail=1; say "PROBE-001 inconclusive"; fi

# BUG-002 — _retry_pending_runs_once contains no update_pid call (the orphan
# launch path does, at line ~3078). CONFIRM absence in the retry body.
body=$(awk '/^def _retry_pending_runs_once/,/^def collect_harness_run/' "$PR")
if ! printf '%s' "$body" | grep -q 'update_pid'; then
  say "CONFIRMED BUG-002: _retry_pending_runs_once has no update_pid call (orchestrator path has it at $(grep -n 'update_pid' "$PR" | head -1 | cut -d: -f1))"
else fail=1; say "PROBE-002 inconclusive"; fi

# BUG-003 — _launch_one_run_detached's returned dict has no "state" key.
body=$(awk '/^def _launch_one_run_detached/,/^def _relpath_for_manifest/' "$PR")
ret=$(printf '%s' "$body" | awk '/^    return \{/,/^    \}/')
if ! printf '%s' "$ret" | grep -q '"state"'; then
  say 'CONFIRMED BUG-003: _launch_one_run_detached return dict has no "state" key (relaunch keeps state=PENDING)'
else fail=1; say "PROBE-003 inconclusive"; fi

# BUG-004 — _PHASE_ARTIFACTS maps QUALITY.md to phase 5 (a Phase-2 output).
if grep -nE '5: *\("QUALITY.md",\)' "$ST" >/dev/null; then
  say "CONFIRMED BUG-004: $ST maps QUALITY.md to phase 5 ($(grep -nE '5: *\("QUALITY.md' "$ST" | head -1)); run_playbook.py:1522 lists it as a Phase-2 prerequisite ($(grep -n 'QUALITY.md' bin/run_playbook.py | sed -n '1p' | cut -d: -f1))"
else fail=1; say "PROBE-004 inconclusive"; fi

# BUG-005 — _entry_is_active returns True when a pid=0 entry's started_at is None.
body=$(awk '/^def _entry_is_active/,/^def read_active_runs/' "$IR")
if printf '%s' "$body" | grep -A1 'if started is None:' | grep -q 'return True'; then
  ln=$(grep -n 'if started is None:' "$IR" | head -1 | cut -d: -f1)
  say "CONFIRMED BUG-005: $IR:$ln 'if started is None: return True' — pid=0 + malformed started_at active forever"
else fail=1; say "PROBE-005 inconclusive"; fi

if [ "$fail" -eq 0 ]; then say "ALL PROBES CONFIRMED"; else say "SOME PROBES INCONCLUSIVE"; fi
exit "$fail"
