#!/usr/bin/env python3
"""Rebuild the status index in evidence/README.md from each folder's STATUS.md.

Every bug folder under evidence/ carries a STATUS.md with these lines:

    status: <one of STATUSES below>
    title: <one-line description>
    link: <PR / issue / commit URL, or ->
    updated: <YYYY-MM-DD>
    note: <one line>

Changing a bug's status means editing that one file and re-running this script.
Folders never move, so links into them stay valid.

Usage:  python3 evidence/build_index.py          (rewrites README.md in place)
        python3 evidence/build_index.py --check  (exit 1 if README.md is stale)
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
README = os.path.join(HERE, "README.md")
BEGIN = "<!-- BEGIN STATUS INDEX (generated by build_index.py; edit STATUS.md files, not this table) -->"
END = "<!-- END STATUS INDEX -->"

STATUSES = [
    ("merged", "Merged upstream"),
    ("open", "Submitted, open"),
    ("sent", "Sent to a mailing list"),
    ("ready", "Ready: reviewed, not yet presented to Andrew under SUBMISSION-PROTOCOL.md"),
    ("needs-work", "Needs work before it can go out"),
    ("held", "Held"),
    ("decision", "Waiting on Andrew's decision"),
    ("dropped", "Dropped"),
    ("not-filed", "Not filed (project policy or a failed fix)"),
    ("duplicate", "Already reported upstream"),
    ("maintainer-view", "Needs a maintainer's view rather than a patch"),
    ("ruled-out", "Ruled out (intended behaviour)"),
]
KNOWN = {s for s, _ in STATUSES}


def read_status(folder):
    fields = {}
    with open(os.path.join(HERE, folder, "STATUS.md"), encoding="utf-8") as f:
        for line in f:
            if ":" in line:
                key, value = line.split(":", 1)
                fields[key.strip()] = value.strip()
    if fields.get("status") not in KNOWN:
        sys.exit(f"{folder}/STATUS.md: unknown status {fields.get('status')!r}")
    return fields


def build():
    folders = sorted(
        d for d in os.listdir(HERE)
        if os.path.isfile(os.path.join(HERE, d, "STATUS.md"))
    )
    rows = {s: [] for s in KNOWN}
    for d in folders:
        f = read_status(d)
        link = f.get("link", "-")
        link_md = f"[link]({link})" if link.startswith("http") else ""
        rows[f["status"]].append(
            f"| [{d}](./{d}/) | {f.get('title', '')} | {link_md} | {f.get('note', '')} | {f.get('updated', '')} |"
        )
    out = [BEGIN, ""]
    for status, heading in STATUSES:
        if not rows[status]:
            continue
        out += [f"### {heading} ({len(rows[status])})", "",
                "| folder | bug | link | note | updated |", "|---|---|---|---|---|"]
        out += rows[status] + [""]
    out.append(END)
    return "\n".join(out)


def main():
    text = open(README, encoding="utf-8").read()
    if BEGIN not in text or END not in text:
        sys.exit("README.md has no status-index markers")
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    new = head + build() + tail
    if "--check" in sys.argv:
        sys.exit(0 if new == text else 1)
    with open(README, "w", encoding="utf-8") as f:
        f.write(new)


if __name__ == "__main__":
    main()
