from pathlib import Path
import json,subprocess
out=Path('docs/research/triage-2026-09-27/nonlinux');revs=json.loads((out/'evidence/upstream-revisions.json').read_text())
base='repos/secbench2_widenet/'
items=[
('NL-01','aiohttp','StreamReader.readuntil misses delimiter spanning buffer chunks',base+'wn-py-09-aiohttp/quality/BUGS.md','BUG-006','verified','actual-implementation execution','potentially_unreported','aiohttp-actual.log',[],1,'Documented read-until-byte-sequence contract; one-buffer vs two-buffer control.','Medium correctness / framing impact; no remotely exploitable security claim established.'),
('NL-02','flatted','Python stringify merges distinct equal composites into aliases',base+'wn-jsts-01-flatted/quality/BUGS.md','BUG-002','unresolved','actual-implementation execution','unknown','flatted-actual.log',[],2,'JS reference preserves identity; current Python own test expects equality dedup, so intent conflict remains.','Medium data topology corruption, subject to contract adjudication.'),
('NL-03','chi','SupressNotFound pollutes live RoutePattern','repos/chi-1.5.8/quality/BUGS.md','BUG-002','verified','actual-implementation execution','related_previously_disclosed','chi-actual.log',['https://github.com/go-chi/chi/issues/939','https://github.com/go-chi/chi/pull/940'],3,'RoutePattern reports matched route; adding only preflight middleware duplicates it. Prior report exposes same mutable-context root cause.','Low/medium instrumentation impact in executed case; historical high label not adopted.'),
('NL-04','chi','ContentCharset rejects valid quoted charset on nonempty request','repos/chi-1.5.8/quality/BUGS.md','BUG-005','verified','actual-implementation execution','previously_disclosed','chi-actual.log',['https://github.com/go-chi/chi/pull/1139'],None,'Go mime.ParseMediaType accepts quoted/unquoted utf-8; ContentCharset claims to admit allowed charsets.','Low/medium valid-request rejection; empty-body bypass is a compensating guard.'),
('NL-05','chi','Compression uses gzip even when q=0 and for x-gzip','repos/chi-1.5.8/quality/BUGS.md','BUG-001','verified','actual-implementation execution','previously_disclosed','chi-actual.log',['https://github.com/go-chi/chi/issues/1069','https://github.com/go-chi/chi/pull/1177'],None,'Accept-Encoding rejection semantics; exact source matches strings.Contains.','Medium interoperability; no new submission warranted while many duplicate PRs exist.'),
('NL-06','ljharb-shell-quote','Special shell parameter drops first trailing character',base+'wn-jsts-02-shell-quote/quality/BUGS.md','BUG-001','verified','actual-implementation execution','previously_disclosed','shell-quote-actual.log',['https://github.com/ljharb/shell-quote/pull/30'],None,'README interpolates variables and existing test/env.js supports special parameters; no syntax justifies dropping following literal.','Medium argument corruption; historical high severity not adopted without impact context.'),
('NL-07','minimatch','POSIX print class matches controls instead of printable characters',base+'wn-jsts-06-minimatch/quality/BUGS.md','BUG-001','unresolved','source inspection only','previously_disclosed',None,['https://github.com/isaacs/minimatch/pull/309'],None,'Current table misses negation flag; exact open PR already supplies reproduction.','Medium correctness; no fresh implementation execution performed here.'),
('NL-08','defu','DefuInstance promises function properties absent from runtime',base+'wn-jsts-05-defu/quality/BUGS.md','BUG-001','unresolved','source inspection only','previously_disclosed',None,['https://github.com/unjs/defu/pull/174'],None,'src/types.ts fn/arrayFn/extend declarations vs bare createDefu function cast.','Low public type/runtime mismatch; exact open PR exists.'),
('NL-09','immutable-js','Repeat.lastIndexOf returns size instead of size minus one',base+'wn-jsts-03-immutable-js/quality/BUGS.md','BUG-001','rejected','source inspection only','fixed_and_previously_disclosed',None,['https://github.com/immutable-js/immutable-js/pull/2227','https://github.com/immutable-js/immutable-js/security/advisories/GHSA-wf6x-7x77-mvgw'],None,'Current src/Repeat.js returns size-1 and guards size zero; current changelog records fix in 5.1.7.','Not a current defect; historical report date June23 is after public fix June22.')]
records=[]
for fid,project,title,path,hid,valid,basis,disclosure,log,links,rank,expected,impact in items:
 p=Path(path);repo=p.parent.parent
 try:hist=subprocess.check_output(['git','-C',str(repo),'rev-parse','HEAD'],text=True,stderr=subprocess.DEVNULL).strip()
 except:hist=None
 records.append({'finding_id':fid,'project':project,'title':title,'historical_report':path,'historical_finding_id':hid,'historical_local_checkout_head':hist,'historical_head_warning':'Local checkout HEAD is not proven discovery revision; artifacts may predate current checkout.','current_upstream':revs[project],'validity':valid,'validation_basis':basis,'prior_disclosure':disclosure,'upstream_links':links,'fresh_evidence':str(out/'evidence'/log) if log else None,'new_submission_rank':rank,'expected_behavior_argument':expected,'impact':impact,'adjudicator':'Codex Sol historical triage subagent; human review pending','date':'2026-09-27'})
(out/'candidates.json').write_text(json.dumps(records,indent=2)+'\n')
