// Regression tests — go-chi/chi v1.5.8 (Quality Playbook Phase 3)
//
// Generated by Quality Playbook v1.5.8 — https://github.com/andrewstellman/quality-playbook
// Date: 2026-06-19 · Project: go-chi/chi v1.5.8
//
// These tests assert the DESIRED CORRECT behavior for each confirmed BUG and are guarded with
// t.Skip (Go's earliest-syntactic skip guard). Each guard names the BUG id and the fix patch.
// To run the RED phase, remove the guard and run against the unpatched tree (expect FAIL).
// To run the GREEN phase, remove the guard and apply quality/patches/BUG-NNN-fix.patch (expect ok).
//
// Package is `middleware` so the tests can reach the package's own unexported parsers
// (matchAcceptEncoding, realIP, contentEncoding) AND exercise the public chi router for the
// composition bugs (chi is imported by package middleware).
//
// NOTE: this file lives under quality/ as the canonical regression artifact. To execute it,
// it must be placed in the middleware/ package directory (the QPB validation step copies it
// there transiently as middleware/qpb_regression_test.go, runs, then removes it — the source
// tree is never mutated). See quality/results/*.red.log for recorded RED runs.

package middleware

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/go-chi/chi/v5"
)

// BUG-001: matchAcceptEncoding substring-matches, so `gzip;q=0` (explicit rejection) and a bogus
// `xgzip` token both falsely select gzip. Desired: exact comma-token match with non-zero q-value.
func TestBUG001_AcceptEncoding_qZero_and_bogusToken(t *testing.T) {
	t.Skip("BUG-001: matchAcceptEncoding substring match — unskip after applying quality/patches/BUG-001-fix.patch")

	// gzip;q=0 must NOT select gzip (RFC 7231 §5.3.4: q=0 is rejection).
	if matchAcceptEncoding(strings.Split(strings.ToLower("gzip;q=0"), ","), "gzip") {
		t.Errorf("Accept-Encoding %q must NOT select gzip (q=0 is an explicit rejection)", "gzip;q=0")
	}
	// A bogus token that merely contains the coding name must NOT match.
	if matchAcceptEncoding(strings.Split(strings.ToLower("xgzip"), ","), "gzip") {
		t.Errorf("Accept-Encoding %q must NOT select gzip (not a registered coding token)", "xgzip")
	}
	if matchAcceptEncoding(strings.Split(strings.ToLower("notgzip, deflate"), ","), "gzip") {
		t.Errorf("Accept-Encoding %q must NOT select gzip (substring false-positive)", "notgzip, deflate")
	}
	// Sanity: a real, well-formed token still matches (must remain true after the fix).
	if !matchAcceptEncoding(strings.Split(strings.ToLower("gzip, deflate"), ","), "gzip") {
		t.Errorf("Accept-Encoding %q must select gzip", "gzip, deflate")
	}
}

// BUG-002: SupressNotFound passes the LIVE rctx into rctx.Routes.Match (mux.go documents that
// Match mutates the *Context — "make a NewRouteContext()"). The probe walk appends to the live
// rctx.RoutePatterns, so the subsequently-served handler observes a CORRUPTED (doubled)
// RoutePattern(). Desired: SupressNotFound uses a throwaway context, leaving the live rctx clean
// so RoutePattern() reports the real pattern exactly once.
func TestBUG002_SupressNotFound_LiveContextMutation(t *testing.T) {
	t.Skip("BUG-002: SupressNotFound mutates live routing context — unskip after applying quality/patches/BUG-002-fix.patch")

	r := chi.NewRouter()
	r.Use(SupressNotFound(r))
	var seenPattern string
	r.Get("/users/{id}", func(w http.ResponseWriter, req *http.Request) {
		seenPattern = chi.RouteContext(req.Context()).RoutePattern()
		w.WriteHeader(200)
	})

	req := httptest.NewRequest("GET", "/users/42", nil)
	rec := httptest.NewRecorder()
	r.ServeHTTP(rec, req)

	if rec.Code != 200 {
		t.Fatalf("GET /users/42 should be served; got %d", rec.Code)
	}
	// The probe Match must not pollute the live context: RoutePattern() must be the single,
	// correct pattern, NOT a doubled "/users/{id}/users/{id}".
	if seenPattern != "/users/{id}" {
		t.Errorf("SupressNotFound must not corrupt the live RoutePattern via the probe Match; want %q got %q", "/users/{id}", seenPattern)
	}
}

// BUG-003: PageRoute (and PathRewrite) compare/rewrite r.URL.Path, never matching the canonical
// mounted path. Desired: PageRoute("/status") fires for /admin/status when mounted at /admin.
func TestBUG003_PageRoute_PathRewrite_UnderMount(t *testing.T) {
	t.Skip("BUG-003: PageRoute/PathRewrite raw-path under Mount — unskip after applying quality/patches/BUG-003-fix.patch")

	child := chi.NewRouter()
	fired := false
	child.Use(PageRoute("/status", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fired = true
		w.WriteHeader(200)
	})))
	// A fallback route so the request is otherwise routable.
	child.Get("/other", func(w http.ResponseWriter, r *http.Request) { w.WriteHeader(204) })

	root := chi.NewRouter()
	root.Mount("/admin", child)

	req := httptest.NewRequest("GET", "/admin/status", nil)
	rec := httptest.NewRecorder()
	root.ServeHTTP(rec, req)

	if !fired || rec.Code != 200 {
		t.Errorf("PageRoute(\"/status\") under Mount(\"/admin\") should fire for /admin/status; got fired=%v status=%d", fired, rec.Code)
	}
}

// BUG-004: realIP does not TrimSpace the leftmost X-Forwarded-For element before net.ParseIP,
// so a space-padded first element is dropped and RemoteAddr is left unchanged.
// Desired: the leftmost element is trimmed and parsed.
func TestBUG004_RealIP_TrimsLeftmostXFF(t *testing.T) {
	t.Skip("BUG-004: realIP no-trim leftmost XFF — unskip after applying quality/patches/BUG-004-fix.patch")

	req := httptest.NewRequest("GET", "/", nil)
	// Leading space before the first element (RFC 7230 OWS after the comma list is permitted;
	// a producer may also pad the first element).
	req.Header.Set("X-Forwarded-For", " 203.0.113.7, 10.0.0.1")

	got := realIP(req)
	if got != "203.0.113.7" {
		t.Errorf("realIP should trim and parse the padded leftmost XFF element; want %q got %q", "203.0.113.7", got)
	}
}

// BUG-005: contentEncoding does not strip quotes from a quoted charset, so charset="utf-8"
// (RFC 2046 quoted parameter value) fails to match the allow-list entry utf-8.
// Desired: a quoted charset matches.
func TestBUG005_ContentCharset_QuotedCharset(t *testing.T) {
	t.Skip("BUG-005: contentEncoding quoted charset — unskip after applying quality/patches/BUG-005-fix.patch")

	if !contentEncoding(`text/plain; charset="utf-8"`, "utf-8") {
		t.Errorf(`Content-Type %q should match charset utf-8 (RFC 2046 quoted param value)`, `text/plain; charset="utf-8"`)
	}
	// Sanity: the unquoted form must still match after the fix.
	if !contentEncoding(`text/plain; charset=utf-8`, "utf-8") {
		t.Errorf(`Content-Type %q should match charset utf-8`, `text/plain; charset=utf-8`)
	}
}

// BUG-006: Mux.Find performs the RoutePath shift but omits the wildcard-URLParam reset the live
// mount closure does, so Find against a mounted route leaves a stale "*" URLParam.
// Desired: after Find on a mounted route, the connecting "*" URLParam is cleared (as the live
// walk leaves it).
func TestBUG006_Find_MountedWildcardURLParamReset(t *testing.T) {
	t.Skip("BUG-006: Find omits wildcard-URLParam reset — unskip after applying quality/patches/BUG-006-fix.patch")

	child := chi.NewRouter()
	child.Get("/ping", func(w http.ResponseWriter, r *http.Request) {})
	root := chi.NewRouter()
	root.Mount("/api", child)

	rctx := chi.NewRouteContext()
	pattern := root.Find(rctx, "GET", "/api/ping")
	if pattern == "" {
		t.Fatalf("Find should locate /api/ping")
	}
	// The live walk zeroes the connecting "*" URLParam (mux.go:316-319). Find must agree:
	// the residual "*" URLParam must be empty, not the leftover mount-relative remainder.
	if star := rctx.URLParam("*"); star != "" {
		t.Errorf("Find on a mounted route must clear the connecting \"*\" URLParam (live walk does); got %q", star)
	}
}

// BUG-007: replaceWildcards collapses any "/*/"→"/" textually, erasing a legitimate literal
// interior "*" segment in the reported RoutePattern. Desired: an interior literal "*" survives.
//
// This test exercises replaceWildcards directly (the textual collapse cited at context.go:139-144).
func TestBUG007_RoutePattern_LiteralInteriorWildcard(t *testing.T) {
	t.Skip("BUG-007: replaceWildcards erases literal interior * — unskip after applying quality/patches/BUG-007-fix.patch (note: fix has an EXEMPTION; see writeup)")

	// A reconstructed pattern containing a legitimate interior "*" segment must NOT be collapsed.
	// (replaceWildcards is package chi's; exercised here via the public RoutePattern surface.)
	rctx := chi.NewRouteContext()
	rctx.RoutePatterns = []string{"/files", "/*", "/meta"}
	got := rctx.RoutePattern()
	if !strings.Contains(got, "*") {
		t.Errorf("RoutePattern must preserve a literal interior \"*\" segment; got %q (interior /*/ erased)", got)
	}
}
