// Generated by Quality Playbook v1.5.7 — https://github.com/andrewstellman/quality-playbook
// Author: Andrew Stellman · Date: 2026-06-19 · Project: go-chi/chi v1.5.8
//
// Functional tests for chi's core router + highest-risk middleware, derived from
// quality/REQUIREMENTS.md and quality/QUALITY.md. These tests live in `package middleware`
// so they can both (a) exercise the public router behaviorally and (b) call the package's
// own unexported parsers (matchAcceptEncoding, realIP, contentEncoding, Compressor.selectEncoder).
//
// Convention: each test asserts a behavior the spec/contract commits to. Tests here assert
// behavior that PASSES on the current v1.5.8 tree (correct cohort, consistent maps, canonical
// inputs, and the OBSERVED current behavior of the buggy parsers documented explicitly).
// The spec-VIOLATING edge cases (gzip;q=0 must NOT compress, xgzip must NOT match, padded XFF
// must parse, quoted charset must match, interior-* must survive) are promoted to skip/xfail-
// guarded REGRESSION tests in Phase 3 (quality/test_regression*.go), per the playbook's
// "regression tests assert desired correct behavior" rule. Where a functional test documents
// current-but-wrong behavior, it is annotated `DOCUMENTS DEFECT` and cross-references the REQ.
//
// To run: place this file at the repo root as test_functional_quality_test.go (or run
//   go test -run 'Quality' .   after copying), since Go requires *_test.go naming and the
// package to compile in-tree. See quality/RUN_INTEGRATION_TESTS.md for the harness command.

package middleware

import (
	"bytes"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/go-chi/chi/v5"
)

// ─────────────────────────────────────────────────────────────────────────────
// Group 1: Spec Requirements — one test per testable requirement/contract
// ─────────────────────────────────────────────────────────────────────────────

// [Req: formal — RFC 7231 §5.3.4; REQ-002 / C-CMP-2]
// Canonical single-coding Accept-Encoding selects that coding. Baseline correctness.
func TestQuality_AcceptEncoding_CanonicalGzipSelected(t *testing.T) {
	c := NewCompressor(5, "text/html")
	h := http.Header{}
	h.Set("Accept-Encoding", "gzip")
	_, name, _ := c.selectEncoder(h, &bytes.Buffer{})
	if name != "gzip" {
		t.Fatalf("expected gzip selected for Accept-Encoding: gzip, got %q", name)
	}
}

// [Req: formal — RFC 7231; REQ-002 / C-CMP-2]  DOCUMENTS DEFECT
// matchAcceptEncoding is a substring match, so a q=0 rejection still matches. This test
// pins the CURRENT (wrong) behavior so a future fix flips it; the desired behavior is
// asserted by the REGRESSION test BUG (gzip;q=0 must NOT select gzip), REQ-002.
func TestQuality_MatchAcceptEncoding_SubstringCurrentBehavior(t *testing.T) {
	if !matchAcceptEncoding([]string{"gzip;q=0"}, "gzip") {
		t.Skip("behavior changed: gzip;q=0 no longer substring-matches — update REQ-002 regression status")
	}
	if !matchAcceptEncoding([]string{"xgzip"}, "gzip") {
		t.Skip("behavior changed: xgzip no longer substring-matches — update REQ-002 regression status")
	}
	// Current code: both match. This documents the defect surface for REQ-002 / REQ-007.
	t.Log("DOCUMENTS DEFECT (REQ-002): substring match accepts gzip;q=0 and xgzip; see regression BUG")
}

// [Req: inferred — REQ-002 / C-RIP-1]
// realIP prefers True-Client-IP over X-Real-IP over X-Forwarded-For, and parses a clean IP.
func TestQuality_RealIP_PrefersTrueClientIP(t *testing.T) {
	r := httptest.NewRequest("GET", "/", nil)
	r.Header.Set("True-Client-IP", "203.0.113.7")
	r.Header.Set("X-Real-IP", "198.51.100.2")
	r.Header.Set("X-Forwarded-For", "192.0.2.1")
	if got := realIP(r); got != "203.0.113.7" {
		t.Fatalf("expected True-Client-IP to win, got %q", got)
	}
}

// [Req: inferred — REQ-002 / C-RIP-1]
// A clean (unpadded) leftmost XFF element parses correctly.
func TestQuality_RealIP_CleanXFFFirstElement(t *testing.T) {
	r := httptest.NewRequest("GET", "/", nil)
	r.Header.Set("X-Forwarded-For", "203.0.113.1, 10.0.0.1")
	if got := realIP(r); got != "203.0.113.1" {
		t.Fatalf("expected leftmost XFF element, got %q", got)
	}
}

// [Req: formal — RFC 7230 OWS; REQ-002 / C-RIP-1]  DOCUMENTS DEFECT
// A space-padded leftmost element is rejected by net.ParseIP because realIP does not
// TrimSpace. Current behavior: returns "". Desired behavior (REQ-002 regression): "203.0.113.1".
func TestQuality_RealIP_PaddedXFFCurrentBehavior(t *testing.T) {
	r := httptest.NewRequest("GET", "/", nil)
	r.Header.Set("X-Forwarded-For", " 203.0.113.1, 10.0.0.1")
	got := realIP(r)
	if got == "203.0.113.1" {
		t.Skip("behavior changed: padded XFF now trimmed — update REQ-002 regression status")
	}
	if got != "" {
		t.Fatalf("expected current (defective) empty result for padded XFF, got %q", got)
	}
	t.Log("DOCUMENTS DEFECT (REQ-002): padded XFF first element drops to empty (no TrimSpace)")
}

// [Req: formal — RFC 2046; REQ-002 / C-CHS-1]
// Unquoted charset matches.
func TestQuality_ContentEncoding_UnquotedCharsetMatches(t *testing.T) {
	if !contentEncoding("text/plain; charset=utf-8", "utf-8") {
		t.Fatalf("expected unquoted charset=utf-8 to match allow-set {utf-8}")
	}
}

// [Req: formal — RFC 2046 quoted-string; REQ-002 / C-CHS-2]  DOCUMENTS DEFECT
// Quoted charset does NOT match because split trims whitespace but not quotes.
// Desired behavior (REQ-002 regression): quoted charset matches.
func TestQuality_ContentEncoding_QuotedCharsetCurrentBehavior(t *testing.T) {
	if contentEncoding(`text/plain; charset="utf-8"`, "utf-8") {
		t.Skip("behavior changed: quoted charset now matches — update REQ-002 regression status")
	}
	t.Log("DOCUMENTS DEFECT (REQ-002): charset=\"utf-8\" (quoted) fails to match {utf-8}")
}

// [Req: inferred — REQ-006 / C-CMP-4]
// isCompressible accepts a whitelisted type and rejects a non-whitelisted type.
func TestQuality_IsCompressible_OnlyWhitelisted(t *testing.T) {
	cw := &compressResponseWriter{
		ResponseWriter:   httptest.NewRecorder(),
		contentTypes:     map[string]struct{}{"application/json": {}},
		contentWildcards: map[string]struct{}{},
	}
	cw.Header().Set("Content-Type", "application/json; charset=utf-8")
	if !cw.isCompressible() {
		t.Fatalf("expected application/json to be compressible")
	}
	cw.Header().Set("Content-Type", "application/pdf")
	if cw.isCompressible() {
		t.Fatalf("expected application/pdf to be NOT compressible")
	}
}

// [Req: inferred — REQ-006 / C-CMP-4]
// A configured type/* wildcard makes matching subtypes compressible.
func TestQuality_IsCompressible_WildcardConfigured(t *testing.T) {
	cw := &compressResponseWriter{
		ResponseWriter:   httptest.NewRecorder(),
		contentTypes:     map[string]struct{}{},
		contentWildcards: map[string]struct{}{"text": {}},
	}
	cw.Header().Set("Content-Type", "text/markdown")
	if !cw.isCompressible() {
		t.Fatalf("expected text/* wildcard to make text/markdown compressible")
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Group 2: Fitness Scenarios — 1:1 with QUALITY.md scenarios (behavioral, via router)
// ─────────────────────────────────────────────────────────────────────────────

// QUALITY.md Scenario 1 / REQ-001 — SupressNotFound under Mount.  DOCUMENTS DEFECT
// Reads raw r.URL.Path, so a mounted valid route is wrongly 404'd. Current behavior pinned;
// desired behavior (200) is the REQ-001 regression target.
func TestQuality_Scenario1_SupressNotFound_MountedMisroutes(t *testing.T) {
	child := chi.NewRouter()
	child.Use(SupressNotFound(child))
	child.Get("/ping", func(w http.ResponseWriter, r *http.Request) { w.WriteHeader(200) })

	root := chi.NewRouter()
	root.Mount("/api", child)

	ts := httptest.NewServer(root)
	defer ts.Close()

	resp, _ := doGet(t, ts.URL+"/api/ping")
	if resp == 404 {
		t.Log("DOCUMENTS DEFECT (REQ-001): SupressNotFound 404s a valid mounted /api/ping (reads raw URL)")
		return
	}
	if resp != 200 {
		t.Fatalf("expected 200 (fixed) or 404 (defect), got %d", resp)
	}
}

// QUALITY.md Scenario 9 / REQ-001 — PathRewrite invisible under Mount.  DOCUMENTS DEFECT
func TestQuality_Scenario9_PathRewrite_MountedInvisible(t *testing.T) {
	child := chi.NewRouter()
	child.Use(PathRewrite("/old", "/new"))
	hit := ""
	child.Get("/new", func(w http.ResponseWriter, r *http.Request) { hit = "new"; w.WriteHeader(200) })
	child.Get("/old", func(w http.ResponseWriter, r *http.Request) { hit = "old"; w.WriteHeader(200) })

	root := chi.NewRouter()
	root.Mount("/svc", child)
	ts := httptest.NewServer(root)
	defer ts.Close()

	doGet(t, ts.URL+"/svc/old")
	if hit == "old" {
		t.Log("DOCUMENTS DEFECT (REQ-001): PathRewrite rewrote r.URL.Path but chi routed canonical /old")
		return
	}
	if hit != "new" {
		t.Fatalf("expected /new (fixed) or /old (defect) handler, got %q", hit)
	}
}

// QUALITY.md Scenario 4 / REQ-003 — method maps consistent, Allow header correct.
func TestQuality_Scenario4_AllowHeader_ListsRegisteredMethods(t *testing.T) {
	r := chi.NewRouter()
	r.Get("/x", func(w http.ResponseWriter, req *http.Request) {})
	r.Post("/x", func(w http.ResponseWriter, req *http.Request) {})

	req := httptest.NewRequest("DELETE", "/x", nil)
	rr := httptest.NewRecorder()
	r.ServeHTTP(rr, req)

	if rr.Code != 405 {
		t.Fatalf("expected 405 for DELETE on GET/POST route, got %d", rr.Code)
	}
	// chi adds each allowed method as a SEPARATE Allow header value (mux.go:518-526 uses
	// w.Header().Add), so read all values, not just the first via .Get.
	allow := strings.Join(rr.Header().Values("Allow"), ", ")
	if !strings.Contains(allow, "GET") || !strings.Contains(allow, "POST") {
		t.Fatalf("Allow header must list GET and POST, got %q", allow)
	}
}

// QUALITY.md Scenario 7 / REQ-005 — trailing wildcard preserved in RoutePattern.
func TestQuality_Scenario7_RoutePattern_PreservesTrailingWildcard(t *testing.T) {
	r := chi.NewRouter()
	var pattern string
	r.Get("/files/*", func(w http.ResponseWriter, req *http.Request) {
		pattern = chi.RouteContext(req.Context()).RoutePattern()
	})
	req := httptest.NewRequest("GET", "/files/a/b/c", nil)
	r.ServeHTTP(httptest.NewRecorder(), req)
	if !strings.HasSuffix(pattern, "/*") {
		t.Fatalf("expected RoutePattern to end with /* for /files/* route, got %q", pattern)
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Group 3: Boundaries and Edge Cases — reference cohort + defensive patterns
// ─────────────────────────────────────────────────────────────────────────────

// [Req: inferred — REQ-001 / C-STR-1] reference cohort: StripSlashes uses RoutePath under Mount.
func TestQuality_StripSlashes_UsesRoutePathUnderMount(t *testing.T) {
	child := chi.NewRouter()
	child.Use(StripSlashes)
	ok := false
	child.Get("/ping", func(w http.ResponseWriter, r *http.Request) { ok = true; w.WriteHeader(200) })

	root := chi.NewRouter()
	root.Mount("/api", child)
	ts := httptest.NewServer(root)
	defer ts.Close()

	// trailing slash should be stripped via canonical RoutePath and still route under mount
	code, _ := doGet(t, ts.URL+"/api/ping/")
	if !ok || code != 200 {
		t.Fatalf("StripSlashes (reference cohort) must route /api/ping/ to /ping under mount; code=%d ok=%v", code, ok)
	}
}

// [Req: inferred — REQ-001 / C-URF-1] reference cohort: URLFormat updates RoutePath under Mount.
func TestQuality_URLFormat_UsesRoutePathUnderMount(t *testing.T) {
	child := chi.NewRouter()
	child.Use(URLFormat)
	gotFormat := ""
	child.Get("/articles", func(w http.ResponseWriter, r *http.Request) {
		gotFormat, _ = chi.RouteContext(r.Context()).URLParam("__urlfmt__"), "" // placeholder; format is in context value
		_ = gotFormat
		w.WriteHeader(200)
	})
	root := chi.NewRouter()
	root.Mount("/api", child)
	ts := httptest.NewServer(root)
	defer ts.Close()

	code, _ := doGet(t, ts.URL+"/api/articles.json")
	if code != 200 {
		t.Fatalf("URLFormat (reference cohort) must strip .json from canonical RoutePath under mount and route /articles; code=%d", code)
	}
}

// [Req: inferred — REQ-001 / C-GHD-1] reference cohort: GetHead routes HEAD to GET under Mount.
func TestQuality_GetHead_RoutesHeadToGetUnderMount(t *testing.T) {
	child := chi.NewRouter()
	child.Use(GetHead)
	child.Get("/health", func(w http.ResponseWriter, r *http.Request) { w.WriteHeader(204) })
	root := chi.NewRouter()
	root.Mount("/api", child)
	ts := httptest.NewServer(root)
	defer ts.Close()

	req, _ := http.NewRequest("HEAD", ts.URL+"/api/health", nil)
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatalf("HEAD request failed: %v", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != 204 {
		t.Fatalf("GetHead (reference cohort) must route HEAD /api/health to GET handler under mount, got %d", resp.StatusCode)
	}
}

// [Req: inferred — REQ-001 / C-PGR-1] PageRoute at TOP LEVEL works (the defect is under Mount).
func TestQuality_PageRoute_TopLevelMatches(t *testing.T) {
	r := chi.NewRouter()
	hit := false
	r.Use(PageRoute("/status", http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		hit = true
		w.WriteHeader(200)
	})))
	r.Get("/other", func(w http.ResponseWriter, req *http.Request) {})

	req := httptest.NewRequest("GET", "/status", nil)
	r.ServeHTTP(httptest.NewRecorder(), req)
	if !hit {
		t.Fatalf("PageRoute must fire for top-level /status (where URL.Path == RoutePath)")
	}
}

// [Req: inferred — REQ-007 / C-CMP-5,6] no Content-Encoding when content type is not compressible.
func TestQuality_Compress_NoEncodingForNonCompressibleType(t *testing.T) {
	r := chi.NewRouter()
	r.Use(Compress(5, "text/html"))
	r.Get("/bin", func(w http.ResponseWriter, req *http.Request) {
		w.Header().Set("Content-Type", "application/octet-stream")
		w.WriteHeader(200)
		w.Write([]byte("rawbytes"))
	})
	ts := httptest.NewServer(r)
	defer ts.Close()

	req, _ := http.NewRequest("GET", ts.URL+"/bin", nil)
	req.Header.Set("Accept-Encoding", "gzip")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatalf("request failed: %v", err)
	}
	defer resp.Body.Close()
	if ce := resp.Header.Get("Content-Encoding"); ce != "" {
		t.Fatalf("non-compressible content type must not get Content-Encoding, got %q", ce)
	}
}

// [Req: inferred — REQ-002 / C-CHS-1] empty charset allows missing Content-Type.
func TestQuality_ContentCharset_EmptyAllowsNoContentType(t *testing.T) {
	// ContentCharset("") allows requests with no charset / no Content-Type.
	if !contentEncoding("", "") {
		t.Fatalf("empty allow-set entry must match empty/absent charset")
	}
}

// [Req: inferred — REQ-003] AllowContentType whitelist rejects an unlisted type with 415.
func TestQuality_AllowContentType_RejectsUnlisted(t *testing.T) {
	r := chi.NewRouter()
	r.Use(AllowContentType("application/json"))
	r.Post("/x", func(w http.ResponseWriter, req *http.Request) { w.WriteHeader(200) })

	req := httptest.NewRequest("POST", "/x", strings.NewReader("{}"))
	req.Header.Set("Content-Type", "text/xml")
	rr := httptest.NewRecorder()
	r.ServeHTTP(rr, req)
	if rr.Code != http.StatusUnsupportedMediaType {
		t.Fatalf("expected 415 for unlisted content type, got %d", rr.Code)
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// helpers
// ─────────────────────────────────────────────────────────────────────────────

func doGet(t *testing.T, url string) (int, string) {
	t.Helper()
	resp, err := http.Get(url)
	if err != nil {
		t.Fatalf("GET %s failed: %v", url, err)
	}
	defer resp.Body.Close()
	buf := new(bytes.Buffer)
	buf.ReadFrom(resp.Body)
	return resp.StatusCode, buf.String()
}
