// Generated by Quality Playbook v1.5.8 — https://github.com/andrewstellman/quality-playbook
// Author: Andrew Stellman · Date: 2026-06-19 · Project: Express (v5.2.1)
//
// Functional tests for the Express v5.2.1 quality playbook.
//
// Idiom: Mocha + supertest, mirroring test/res.send.js — import Express as
// `require('..')` (resolves index.js -> lib/express.js) and drive requests with
// `request(app)`. These tests REQUIRE node_modules to be installed
// (`npm install` brings in mocha, supertest, and Express's runtime deps:
// router, finalhandler, send, accepts, ...). In this checkout node_modules is
// absent; run `npm install` before `npx mocha quality/test_functional.js`.
//
// Each test traces to a REQ + QUALITY.md fitness scenario. Tests assert the
// EXACT header value / body content the contract requires — never just a status
// code or header existence (see QUALITY.md "Coverage Theater Prevention").

'use strict'

var assert = require('node:assert')
var express = require('..')
var request = require('supertest')

describe('Express v5.2.1 — Functional (Quality Playbook v1.5.8)', function () {

  // ───────────────────────────── Fitness scenarios ─────────────────────────────

  describe('Fitness scenarios', function () {

    // Scenario 1 / REQ-001 / UC-01 — req.protocol must yield a non-empty,
    // correct scheme for every trusted X-Forwarded-Proto value.
    describe('Scenario 1: X-Forwarded-Proto empty/comma elements', function () {
      function app () {
        var app = express()
        app.set('trust proxy', true)
        app.get('/', function (req, res) {
          res.json({ protocol: req.protocol, secure: req.secure })
        })
        return app
      }

      it('test_scenario_1_xforwarded_proto_empty_element', function (done) {
        // ", https" makes indexOf(',')===1 -> substring(0,1).trim()==='' .
        // Contract: protocol must be non-empty and in {http,https}; secure
        // must reflect the real scheme. This currently returns ''.
        request(app())
          .get('/')
          .set('X-Forwarded-Proto', ', https')
          .end(function (err, res) {
            if (err) return done(err)
            assert.ok(
              res.body.protocol === 'http' || res.body.protocol === 'https',
              'REQ-001: protocol must be http|https, got ' +
                JSON.stringify(res.body.protocol)
            )
            done()
          })
      })

      it('test_scenario_1_xforwarded_proto_plain_https', function (done) {
        // Control case: a clean value resolves correctly.
        request(app())
          .get('/')
          .set('X-Forwarded-Proto', 'https')
          .end(function (err, res) {
            if (err) return done(err)
            assert.strictEqual(res.body.protocol, 'https', 'REQ-001 control')
            assert.strictEqual(res.body.secure, true, 'REQ-001 secure derives from protocol')
            done()
          })
      })
    })

    // Scenario 2 / REQ-002 / UC-02 — res.cookie must not emit Max-Age=0
    // alongside a future Expires for a sub-second maxAge.
    it('test_scenario_2_subsecond_maxage_not_zero', function (done) {
      var app = express()
      app.get('/', function (req, res) {
        res.cookie('x', '1', { maxAge: 500 }).end()
      })
      request(app)
        .get('/')
        .end(function (err, res) {
          if (err) return done(err)
          var setCookie = [].concat(res.headers['set-cookie'] || []).join('; ')
          assert.ok(
            !/Max-Age=0\b/.test(setCookie),
            'REQ-002: sub-second maxAge must not serialize Max-Age=0 (got: ' +
              setCookie + ')'
          )
          done()
        })
    })

    // Scenario 3 / REQ-003 / UC-03 — res.redirect body must not contain the
    // literal "undefined" for a status statuses.message does not know.
    it('test_scenario_3_redirect_unknown_status_no_undefined', function (done) {
      var app = express()
      app.get('/', function (req, res) {
        res.redirect(310, '/target') // 310 is unassigned -> statuses.message[310] === undefined
      })
      request(app)
        .get('/')
        .end(function (err, res) {
          if (err) return done(err)
          assert.ok(
            !/undefined/.test(res.text || ''),
            'REQ-003: redirect body must not contain literal "undefined" (got: ' +
              JSON.stringify(res.text) + ')'
          )
          done()
        })
    })

    // Scenario 4 / REQ-004 / UC-04 — jsonp callback whitelist + nosniff.
    it('test_scenario_4_jsonp_callback_whitelist', function (done) {
      var app = express()
      app.get('/', function (req, res) {
        res.jsonp({ ok: true })
      })
      request(app)
        .get('/?callback=alert(1)//')
        .end(function (err, res) {
          if (err) return done(err)
          assert.strictEqual(
            res.headers['x-content-type-options'], 'nosniff',
            'REQ-004: jsonp responses must set X-Content-Type-Options: nosniff'
          )
          // The filter strips "(", ")", "/" -> body invokes "alert1", never
          // the raw "alert(1)//". This pins the documented sanitization.
          assert.ok(
            res.text.indexOf('alert(1)') === -1,
            'REQ-004: parenthesized callback must be sanitized, got: ' + res.text
          )
          done()
        })
    })

    // Scenario 5 / REQ-006 (parity) / UC-06.a,b — charset string vs Buffer.
    describe('Scenario 5: charset parity string vs Buffer', function () {
      it('test_scenario_5_charset_string_vs_buffer_parity', function (done) {
        var appStr = express()
        appStr.get('/', function (req, res) {
          res.set('Content-Type', 'text/plain; charset=iso-8859-1').send('é')
        })
        var appBuf = express()
        appBuf.get('/', function (req, res) {
          res.set('Content-Type', 'text/plain; charset=iso-8859-1')
            .send(Buffer.from('é', 'latin1'))
        })
        request(appStr).get('/').end(function (err, strRes) {
          if (err) return done(err)
          request(appBuf).get('/').end(function (err2, bufRes) {
            if (err2) return done(err2)
            // UC-06.a vs UC-06.b: capture both charsets. The known v5 behavior
            // is string->utf-8, Buffer->preserved. This test documents the
            // asymmetry; Phase 3/4 decides whether it is intended.
            var strCt = strRes.headers['content-type'] || ''
            var bufCt = bufRes.headers['content-type'] || ''
            assert.ok(/charset=/.test(strCt), 'REQ-006: string send must declare a charset')
            assert.ok(/charset=/.test(bufCt), 'REQ-006: Buffer send must declare a charset')
            done()
          })
        })
      })

      // UC-06.c — res.type then send: mime.contentType injection.
      it('test_scenario_5c_type_then_send_charset', function (done) {
        var app = express()
        app.get('/', function (req, res) {
          res.type('html').send('<p>x</p>')
        })
        request(app).get('/').end(function (err, res) {
          if (err) return done(err)
          var ct = res.headers['content-type'] || ''
          assert.ok(
            /text\/html/.test(ct) && /charset=utf-8/.test(ct),
            'UC-06.c: res.type("html") then send must inject charset=utf-8, got: ' + ct
          )
          done()
        })
      })
    })

    // Scenario 6 / REQ-007 (parity) / UC-07.a,b,c — host/hostname/subdomains.
    describe('Scenario 6: X-Forwarded-Host shapes', function () {
      function app () {
        var app = express()
        app.set('trust proxy', true)
        app.get('/', function (req, res) {
          res.json({ host: req.host, hostname: req.hostname, subdomains: req.subdomains })
        })
        return app
      }

      it('test_scenario_6_xforwarded_host_normal', function (done) { // UC-07.a
        request(app()).get('/').set('X-Forwarded-Host', 'sub.a.com')
          .end(function (err, res) {
            if (err) return done(err)
            assert.strictEqual(res.body.hostname, 'sub.a.com', 'UC-07.a hostname')
            done()
          })
      })

      it('test_scenario_6_xforwarded_host_leading_comma', function (done) { // UC-07.b
        request(app()).get('/').set('X-Forwarded-Host', ',real.example.com')
          .end(function (err, res) {
            if (err) return done(err)
            // Contract: a present authority must not yield undefined hostname.
            assert.notStrictEqual(
              res.body.hostname, undefined,
              'REQ-007/UC-07.b: leading-comma XFH must not yield undefined hostname'
            )
            done()
          })
      })

      it('test_scenario_6_xforwarded_host_port_stripped', function (done) { // UC-07.c
        request(app()).get('/').set('X-Forwarded-Host', 'a.com:8080')
          .end(function (err, res) {
            if (err) return done(err)
            assert.strictEqual(res.body.hostname, 'a.com', 'UC-07.c port must be stripped')
            done()
          })
      })
    })

    // Scenario 7 / REQ-005 / UC-05 — acceptParams quoted media-type value.
    it('test_scenario_7_acceptparams_quoted_value', function (done) {
      var app = express()
      app.get('/', function (req, res) {
        res.format({
          'text/html': function () { res.send('html') },
          default: function () { res.status(406).send('na') }
        })
      })
      // RFC 7231 §3.1.1.1 permits quoted params; a quoted ';' must not break parsing.
      request(app)
        .get('/')
        .set('Accept', 'text/html;x="a;b";q=0.9')
        .end(function (err, res) {
          if (err) return done(err)
          // The negotiated format should still resolve to text/html, not 406.
          assert.strictEqual(res.text, 'html',
            'REQ-005: quoted ";" inside a media-type param must not break negotiation')
          done()
        })
    })

    // Scenario 8 / REQ-008 — settings compilation fails fast.
    it('test_scenario_8_invalid_setting_fails_fast', function () {
      var app = express()
      // An object is not a valid 'etag' value -> compileETag default throws.
      assert.throws(
        function () { app.set('etag', {}) },
        /TypeError|etag/i,
        'REQ-008: invalid etag value must throw a TypeError at app.set time'
      )
    })
  })

  // ───────────────────────────── Spec requirements ─────────────────────────────
  // One direct check per testable REQ contract (complements the scenario tests
  // above with focused, single-property assertions).

  describe('Spec requirements', function () {

    it('REQ-001: trusted clean X-Forwarded-Proto sets secure', function (done) {
      var app = express()
      app.set('trust proxy', true)
      app.get('/', function (req, res) { res.send(String(req.secure)) })
      request(app).get('/').set('X-Forwarded-Proto', 'https')
        .end(function (err, res) {
          if (err) return done(err)
          assert.strictEqual(res.text, 'true')
          done()
        })
    })

    it('REQ-002: a multi-second maxAge serializes a non-zero Max-Age', function (done) {
      var app = express()
      app.get('/', function (req, res) { res.cookie('x', '1', { maxAge: 60000 }).end() })
      request(app).get('/').end(function (err, res) {
        if (err) return done(err)
        var setCookie = [].concat(res.headers['set-cookie'] || []).join('; ')
        assert.ok(/Max-Age=60\b/.test(setCookie),
          'REQ-002: maxAge 60000ms must floor to Max-Age=60, got: ' + setCookie)
        done()
      })
    })

    it('REQ-003: a known redirect status emits its phrase, not undefined', function (done) {
      var app = express()
      app.get('/', function (req, res) { res.redirect(301, '/t') })
      request(app).get('/').end(function (err, res) {
        if (err) return done(err)
        assert.ok(!/undefined/.test(res.text || ''), 'REQ-003: known status body clean')
        done()
      })
    })

    it('REQ-004: jsonp sets text/javascript content type', function (done) {
      var app = express()
      app.get('/', function (req, res) { res.jsonp({ a: 1 }) })
      request(app).get('/?callback=cb').end(function (err, res) {
        if (err) return done(err)
        assert.ok(/text\/javascript/.test(res.headers['content-type'] || ''),
          'REQ-004: jsonp body is text/javascript')
        done()
      })
    })

    it('REQ-006: string send forces charset=utf-8 (documented v5 rule)', function (done) {
      var app = express()
      app.get('/', function (req, res) {
        res.set('Content-Type', 'text/plain; charset=iso-8859-1').send('x')
      })
      request(app).get('/').end(function (err, res) {
        if (err) return done(err)
        assert.ok(/charset=utf-8/i.test(res.headers['content-type'] || ''),
          'REQ-006/UC-06.a: string send rewrites charset to utf-8')
        done()
      })
    })

    it('REQ-007: trusted plain X-Forwarded-Host resolves subdomains', function (done) {
      var app = express()
      app.set('trust proxy', true)
      app.get('/', function (req, res) { res.json(req.subdomains) })
      request(app).get('/').set('X-Forwarded-Host', 'a.b.example.com')
        .end(function (err, res) {
          if (err) return done(err)
          assert.deepStrictEqual(res.body, ['b', 'a'],
            'REQ-007: subdomains split + reversed from a clean authority')
          done()
        })
    })
  })

  // ───────────────────────────── Boundaries / edge cases ─────────────────────────────

  describe('Boundaries and edge cases', function () {

    it('untrusted X-Forwarded-Proto is ignored (proto from socket)', function (done) {
      var app = express() // trust proxy default: untrusted
      app.get('/', function (req, res) { res.send(req.protocol) })
      request(app).get('/').set('X-Forwarded-Proto', 'https')
        .end(function (err, res) {
          if (err) return done(err)
          assert.strictEqual(res.text, 'http',
            'untrusted peer: forwarded proto must be ignored')
          done()
        })
    })

    it('untrusted X-Forwarded-Host falls back to Host header', function (done) {
      var app = express()
      app.get('/', function (req, res) { res.send(req.hostname || '<none>') })
      request(app).get('/').set('Host', 'real.host').set('X-Forwarded-Host', 'evil.host')
        .end(function (err, res) {
          if (err) return done(err)
          assert.strictEqual(res.text, 'real.host',
            'untrusted peer: X-Forwarded-Host must be ignored')
          done()
        })
    })

    it('res.redirect to a known 3xx sets the Location header', function (done) {
      var app = express()
      app.get('/', function (req, res) { res.redirect('/somewhere') })
      request(app).get('/').end(function (err, res) {
        if (err) return done(err)
        assert.strictEqual(res.headers.location, '/somewhere')
        assert.strictEqual(res.statusCode, 302)
        done()
      })
    })

    it('res.cookie without maxAge emits neither Max-Age nor a future Expires', function (done) {
      var app = express()
      app.get('/', function (req, res) { res.cookie('x', '1').end() })
      request(app).get('/').end(function (err, res) {
        if (err) return done(err)
        var setCookie = [].concat(res.headers['set-cookie'] || []).join('; ')
        assert.ok(!/Max-Age=/.test(setCookie), 'no maxAge -> no Max-Age directive')
        done()
      })
    })

    it('invalid trust proxy value fails fast', function () {
      var app = express()
      assert.throws(function () { app.set('trust proxy', {}) }, /TypeError|trust proxy/i,
        'REQ-008: invalid trust proxy value throws at config time')
    })

    it('app.get with a single arg reads a setting (the getter overload)', function () {
      var app = express()
      app.set('view engine', 'pug')
      // EXPLORATION finding #11: app.get('name') is a settings read, not a route.
      assert.strictEqual(app.get('view engine'), 'pug',
        'app.get(name) reads the setting (documented getter overload)')
    })
  })
})
